import type { AcceleratorDetail } from "./accelerator-data";

// Sourced from Intel_Crescent_Island_Xe3P_Technical_Reference_v1.0.pdf (compiled 9 Aug 2026;
// throughput/memory-bandwidth figures added 27 Aug 2026 from Intel's published spec table).
export const CRESCENT_ISLAND: AcceleratorDetail = {
  id: "crescent-island",
  name: "Intel Crescent Island",
  codeName: "Xe3P — data-centre inference GPU",
  tagline: "Memory capacity per dollar and per watt, built for agentic AI",
  accent: "#f472b6",
  accentRgb: "244,114,182",
  statusBadge: "Pre-launch — sampling H2 2026, volume 2027",
  overview: [
    "Intel's re-entry into discrete data-centre AI silicon after the Gaudi line was wound down. The design thesis is deliberately narrow: rather than chase training FLOPS, it optimises for memory capacity per dollar and per watt in an air-cooled PCIe form factor, targeting steady-state inference and agentic serving where model residency and context length gate throughput more than peak matrix rate.",
    "Intel has since published the part's compute-throughput and memory-bandwidth specification — the TFLOPS and memory figures below are Intel's own numbers, not a derived estimate.",
  ],
  hwSpecs: [
    { label: "Architecture", value: "Xe3P (performance-optimised Xe3 derivative, \"Celestial\" lineage)" },
    { label: "Primary workload", value: "AI inference — explicitly positioned as \"built for agentic AI\"" },
    { label: "Secondary workload", value: "Scientific / numeric compute via FP64 datapath" },
    { label: "Board power (TDP)", value: "350 W reference and partner-ceiling class" },
    { label: "Cooling", value: "Air-cooled (no liquid loop required)" },
    { label: "Form factor", value: "PCIe add-in card, full-height" },
    { label: "Host interface", value: "PCIe Gen5 x16 (assumed, consistent with 16-pin power precedent)" },
    { label: "Power connector", value: "Single 16-pin 12V-2×6 (leaked)" },
    { label: "Announced / sampling", value: "14 Oct 2025 (OCP) · customer sampling H2 2026 · volume 2027" },
  ],
  memorySpecs: [
    { label: "Memory type", value: "LPDDR5X — no HBM, no GDDR" },
    { label: "Capacity (reference design)", value: "160 GB" },
    { label: "Capacity (partner ceiling)", value: "480 GB" },
    { label: "Memory bandwidth", value: "1.5 TB/s — Intel published" },
    { label: "Memory sites on PCB", value: "20 LPDDR5X packages (12 front, 8 rear) — leaked" },
    { label: "Packaging", value: "No silicon interposer / CoWoS — decoupled from HBM supply constraints" },
    { label: "8-card node memory", value: "Up to 3,840 GB (8 × 480 GB)" },
    { label: "8-card node bandwidth", value: "~12.3 TB/s aggregate (sum of independent cards, not achievable within one tensor-parallel model)" },
  ],
  tflops: [
    { dataType: "FP64", value: "10.2 TFLOPS" },
    { dataType: "FP32", value: "20.5 TFLOPS" },
    { dataType: "BF16", value: "655.5 TFLOPS" },
    { dataType: "FP8", value: "1,311 TFLOPS" },
    { dataType: "MXFP4", value: "2,622 TFLOPS" },
  ],
  swStack: [
    { layer: "Kernel / driver", component: "Linux xe DRM driver", role: "Device enumeration, memory management, scheduling — upstream in mainline" },
    { layer: "Runtime", component: "Intel Compute Runtime (Level Zero, OpenCL)", role: "Low-level device API, command submission — mature on Battlemage" },
    { layer: "Programming model", component: "oneAPI / SYCL (DPC++)", role: "Cross-vendor C++ heterogeneous model, open spec" },
    { layer: "Compiler", component: "Intel Graphics Compiler (IGC) + icpx", role: "SPIR-V / GPU codegen" },
    { layer: "Kernel DSL", component: "intel-xpu-backend-for-triton", role: "Triton kernels on XPU — critical path for new attention kernels" },
    { layer: "Primitives", component: "oneDNN, oneMKL", role: "GEMM, conv, attention primitives" },
    { layer: "Collectives", component: "oneCCL", role: "Multi-GPU all-reduce / all-gather — PCIe P2P dependent" },
    { layer: "Framework", component: "PyTorch xpu device (torch.xpu)", role: "Native upstream backend, no out-of-tree fork required" },
    { layer: "Framework", component: "IPEX (Intel Extension for PyTorch)", role: "Ahead-of-upstream optimisations, being folded upstream" },
    { layer: "Graph runtime", component: "OpenVINO", role: "Most mature Intel inference path; NNCF quantisation" },
    { layer: "LLM serving", component: "vLLM XPU backend", role: "Paged attention, continuous batching, TP — upstream collaboration active since 2025" },
    { layer: "LLM serving", component: "intel/llm-scaler", role: "Containerised vLLM distribution + multi-GPU; vllm-0.14.0-b8.2 added B70 support Apr 2026" },
    { layer: "Agentic", component: "LangChain / Hugging Face / OPEA", role: "Unmodified-code agentic orchestration — Intel's stated \"just works\" target" },
    { layer: "Orchestration", component: "Kubernetes + Intel Device Plugins", role: "Scheduling, allocation, node feature discovery" },
    { layer: "Manageability", component: "ECC, SR-IOV, telemetry, remote FW update", role: "Enterprise reliability and multi-tenancy — delivered in Battlematrix" },
  ],
  caveats: [
    "Dec 2025 Battlematrix testing (the direct software ancestor of this stack) showed only MXFP4 models loading successfully — INT4, FP8 and AWQ quantisations failed outright, and only tensor parallelism worked (expert/pipeline parallelism were non-functional). This has improved through 2026 but remains the primary adoption risk — bring your own model, quantisation and parallelism strategy to acceptance-test on sampling silicon.",
    "No announced proprietary scale-up fabric — PCIe P2P is the multi-card interconnect, so host CPU lane count is a first-order sizing constraint (8 cards × x16 = 128 PCIe Gen5 lanes before NIC/storage).",
    "Workload fit: strong for sparse MoE serving, long-context agentic sessions with prefix reuse, high-concurrency batch inference, many co-resident small models, and embedding/reranker serving. Weak for dense 200B+ low-latency decode and latency-critical single-stream chat — the card is bandwidth-bound at batch 1.",
    "Recommended Xeon 6 host tier for an 8-card node: 6767P (64c/350W) as the baseline, or 6776P for best perf/W if power-constrained (per the Xeon 6 SKU workbook's GPU-host-CPU rows).",
    "Pricing, die size/node, and ECC support are still unconfirmed as of Aug 2026.",
  ],
  sourceNote: "Compiled from Intel Crescent Island (Xe3P) Technical Reference v1.0 (9 Aug 2026; throughput/bandwidth spec table added 27 Aug 2026). TDP, GPU IP, datatype throughput (FP64/FP32/BF16/FP8/MXFP4), and memory (type, capacity, bandwidth) are all Intel-published.",
};
