import type { AcceleratorDetail, SpecRow } from "./accelerator-data";

// Compiled from NVIDIA's public datasheets and product pages (nvidia.com), Aug/Sep 2026.
// These are NVIDIA parts, not Intel — kept in a separate file/accent (NVIDIA green) so the
// Silicon page's GPU catalog clearly distinguishes vendor. Figures marked "with sparsity" are
// NVIDIA's headline marketing numbers (2:4 structured sparsity); the paired dense figure is
// what a model without sparsity-aware weights will actually see. Re-verify against nvidia.com
// before using any of these in a bid or business case.

const NVIDIA_ACCENT = "#76b900";
const NVIDIA_ACCENT_RGB = "118,185,0";

// The Xeon 6 host-pairing rules (row 71-86 of Intel_Xeon6_Workload_SKU_Recommendations.xlsx) are
// identical across every NVIDIA GPU companion reference — only the host-memory sizing derived
// from each GPU's own memory capacity changes. Kept as one function so the five call sites below
// can't drift out of sync with each other.
function xeon6HostRows(gpuMemGb: number, hostMemGb: number, dimms: number): SpecRow[] {
  return [
    { label: "Best-fit SKU — LGA-4710 chassis", value: "Xeon 6776P — 64C / 350 W (6700P socket)" },
    { label: "Best-fit SKU — LGA-7529 chassis", value: "Xeon 6962P — 72C / 500 W (6900P socket, e.g. Supermicro SYS-522GA-NRT)" },
    { label: "GPU-facing PCIe lanes (8-GPU node)", value: "128 (8 × x16 direct-attach)" },
    { label: "Xeon 6700P lanes available (2 sockets)", value: "176 (88 lanes/CPU)" },
    { label: "Host memory ≥ 2× GPU memory", value: `${hostMemGb.toLocaleString()} GB (2 × 8 × ${gpuMemGb} GB)` },
    { label: "DIMMs needed @ 128 GB RDIMM", value: `${dimms} (of 32 slots — 2S × 8ch × 2 DPC; 2 DPC drops to 5200 MT/s)` },
  ];
}

export const NVIDIA_H100: AcceleratorDetail = {
  id: "nvidia-h100",
  name: "NVIDIA H100 SXM5",
  codeName: "Hopper (GH100), TSMC 4N",
  tagline: "The incumbent datacenter GPU — Hopper Tensor Cores, HBM3, NVLink 4",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — widely deployed since 2023",
  overview: [
    "NVIDIA's Hopper-generation flagship, and still the most widely deployed high-end training/inference GPU as of 2026. The SXM5 form factor (as opposed to the lower-power PCIe card) is the variant used in HGX/DGX 8-GPU servers and is what this app's Qwen sizing model defaults to (989 TFLOPS dense BF16, 3.35 TB/s HBM3 — both reproduced exactly below).",
    "A PCIe H100 SKU also exists (350 W, 80 GB HBM2e, ~2 TB/s, no NVLink) with meaningfully lower throughput than SXM5 — see this app's Comparisons tab, which already carries that variant separately. Don't conflate the two when sizing.",
  ],
  hwSpecs: [
    { label: "Architecture", value: "Hopper (GH100), TSMC 4N" },
    { label: "Form factor", value: "SXM5 module (HGX/DGX 8-GPU baseboard)" },
    { label: "Host interface", value: "SXM5 socket (not a PCIe card)" },
    { label: "NVLink", value: "4th generation, 900 GB/s per GPU" },
    { label: "Board power (TDP)", value: "Up to 700 W (configurable)" },
    { label: "Cooling", value: "Air or liquid, depending on HGX chassis" },
  ],
  memorySpecs: [
    { label: "Memory type", value: "HBM3" },
    { label: "Capacity", value: "80 GB" },
    { label: "Memory bandwidth", value: "3.35 TB/s (3,350 GB/s)" },
  ],
  tflops: [
    { dataType: "FP64 (CUDA)", value: "34 TFLOPS" },
    { dataType: "FP64 Tensor Core", value: "67 TFLOPS" },
    { dataType: "FP32 (CUDA)", value: "67 TFLOPS" },
    { dataType: "TF32 Tensor Core", value: "989 TFLOPS", note: "with sparsity — 495 TFLOPS dense" },
    { dataType: "BF16 / FP16 Tensor Core", value: "1,979 TFLOPS", note: "with sparsity — 990 TFLOPS dense (this app's sizing-model default)" },
    { dataType: "FP8 Tensor Core", value: "3,958 TFLOPS", note: "with sparsity — 1,979 TFLOPS dense" },
    { dataType: "INT8 Tensor Core", value: "3,958 TOPS", note: "with sparsity — 1,979 TOPS dense" },
  ],
  swStack: [
    { layer: "Driver / runtime", component: "NVIDIA driver + CUDA runtime", role: "Device management, memory, scheduling — the industry baseline" },
    { layer: "Programming model", component: "CUDA / CUDA-X", role: "The dominant GPU programming model; every major framework targets it first" },
    { layer: "Kernel libraries", component: "cuDNN, cuBLAS, CUTLASS", role: "GEMM, conv, attention primitives — heavily tuned per-architecture" },
    { layer: "Collectives", component: "NCCL", role: "Multi-GPU/multi-node all-reduce, all-gather — NVLink + InfiniBand aware" },
    { layer: "Compiler / DSL", component: "Triton, TensorRT-LLM", role: "Custom kernel authoring; TensorRT-LLM for optimized LLM serving" },
    { layer: "Framework", component: "PyTorch (native CUDA backend)", role: "First-class support, no fork or extension needed" },
    { layer: "LLM serving", component: "vLLM, TensorRT-LLM, Triton Inference Server", role: "Paged attention, continuous batching, tensor/pipeline parallel — most mature ecosystem of any accelerator" },
    { layer: "Orchestration", component: "Kubernetes + NVIDIA GPU Operator", role: "Scheduling, MIG partitioning, device plugin, DCGM telemetry" },
    { layer: "Agentic", component: "NIM microservices, LangChain, Hugging Face", role: "Unmodified-code agentic orchestration — same ecosystem as everyone builds against first" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "4th-gen NVLink, 900 GB/s per GPU" },
    { label: "Host interface", value: "SXM5 socket (not PCIe) — see the PCIe H100 SKU for a PCIe-hosted alternative" },
  ],
  caveats: [
    "SXM5 vs PCIe matters: this card is the SXM5 (HGX/DGX) variant. The PCIe H100 SKU already tracked in this app's Comparisons tab is a different, lower-throughput part (350 W, no NVLink) — don't mix the two when sizing a bid.",
    "\"With sparsity\" figures require the model's weights to actually be pruned to NVIDIA's 2:4 structured-sparsity pattern; an unmodified dense checkpoint gets the dense figure, not the marketing headline.",
    "Being superseded by Blackwell (B200/GB200/GB300) for new large-scale builds, but H100 fleets remain the largest installed base — relevant for capacity planning against existing customer infrastructure.",
  ],
  sourceNote: "Compiled from NVIDIA's public H100 datasheet and widely-published SXM5 specifications (Sep 2026). High-confidence, well-established figures — still verify against nvidia.com before quoting in a bid.",
};

export const NVIDIA_H100_PCIE: AcceleratorDetail = {
  id: "nvidia-h100-pcie",
  name: "NVIDIA H100 PCIe",
  codeName: "Hopper (GH100), TSMC 4N — PCIe card",
  tagline: "The PCIe-hosted H100 — no NVLink, lower clocks than the SXM5 module",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — widely deployed since 2023",
  overview: [
    "The PCIe form factor of NVIDIA's Hopper-generation flagship — a standard dual-slot add-in card rather than the SXM5 module used in HGX/DGX 8-GPU servers. Lower board power (350 W vs. up to 700 W) and no NVLink give it meaningfully lower throughput than SXM5: this app's own Qwen sizing-model default (990 TFLOPS dense BF16) is the SXM5 figure, not this one — don't conflate the two when sizing.",
    "80 GB of HBM2e at ~2 TB/s — a full generation behind SXM5's HBM3 at 3.35 TB/s — but the same mature CUDA/TensorRT-LLM/vLLM software stack, and the more common choice for retrofitting existing PCIe-only server chassis without an HGX baseboard.",
  ],
  hwSpecs: [
    { label: "Architecture", value: "Hopper (GH100), TSMC 4N" },
    { label: "Form factor", value: "PCIe dual-slot, air-cooled" },
    { label: "Host interface", value: "PCIe Gen5 x16" },
    { label: "NVLink", value: "None on this SKU — see the SXM5 module for NVLink-fused scaling" },
    { label: "Board power (TDP)", value: "350 W" },
    { label: "Cooling", value: "Air" },
  ],
  memorySpecs: [
    { label: "Memory type", value: "HBM2e" },
    { label: "Capacity", value: "80 GB" },
    { label: "Memory bandwidth", value: "~2 TB/s (2,039 GB/s)" },
  ],
  tflops: [
    { dataType: "FP64 Tensor Core", value: "51 TFLOPS", note: "26 TFLOPS on standard FP64 CUDA cores" },
    { dataType: "FP32", value: "51 TFLOPS" },
    { dataType: "TF32 Tensor Core", value: "756 TFLOPS", note: "with sparsity — 378 TFLOPS dense" },
    { dataType: "FP16 / BF16 Tensor Core", value: "1,513 TFLOPS", note: "with sparsity — 756 TFLOPS dense" },
    { dataType: "FP8 Tensor Core", value: "3,026 TFLOPS", note: "with sparsity — 1,513 TFLOPS dense" },
    { dataType: "INT8 Tensor Core", value: "3,026 TOPS", note: "with sparsity — 1,513 TOPS dense" },
  ],
  swStack: [
    { layer: "Driver / runtime", component: "NVIDIA driver + CUDA runtime", role: "Device management, memory, scheduling — the industry baseline" },
    { layer: "Programming model", component: "CUDA / CUDA-X", role: "The dominant GPU programming model; every major framework targets it first" },
    { layer: "Kernel libraries", component: "cuDNN, cuBLAS, CUTLASS", role: "GEMM, conv, attention primitives — heavily tuned per-architecture" },
    { layer: "Compiler / DSL", component: "Triton, TensorRT-LLM", role: "Custom kernel authoring; TensorRT-LLM for optimized LLM serving" },
    { layer: "Framework", component: "PyTorch (native CUDA backend)", role: "First-class support, no fork or extension needed" },
    { layer: "LLM serving", component: "vLLM, TensorRT-LLM, Triton Inference Server", role: "Paged attention, continuous batching — same mature ecosystem as SXM5" },
    { layer: "Orchestration", component: "Kubernetes + NVIDIA GPU Operator", role: "Scheduling, MIG partitioning, device plugin, DCGM telemetry" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "None — no NVLink on this SKU; all peer traffic rides PCIe" },
    { label: "PCIe 5.0 x16 per direction", value: "≈63 GB/s" },
    { label: "Scaling guidance", value: "Replicate or pipeline-parallel — no NVLink-fused tensor parallelism, unlike SXM5" },
  ],
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Supported" },
    { label: "MIG (hardware partitions)", value: "Supported — 1g.10gb smallest profile, up to 7 instances/GPU" },
    { label: "MIG-backed vGPU", value: "Supported — 10 GB min, up to 7/GPU" },
    { label: "vGPU time-sliced inside a MIG slice", value: "Not supported" },
    { label: "Time-sliced vGPU (compute, C-series)", value: "Supported — 4 GB min, up to 20/GPU (or 4 GB × 16 in mixed-size mode)" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Not supported" },
    { label: "Smallest isolated (memory-fenced) unit", value: "4 GB" },
    { label: "Max isolated slots / GPU", value: "20 (160 across an 8-GPU node)" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "75%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Required for all vGPU modes above — licensed per physical GPU, not per slice" },
  ],
  caveats: [
    "PCIe vs. SXM5 matters: this is the lower-power, no-NVLink card. The SXM5 module (this app's Qwen sizing-model default, 990 TFLOPS dense BF16) is a materially higher-throughput part — don't mix the two when sizing a bid.",
    "\"With sparsity\" figures require the model's weights to actually be pruned to NVIDIA's 2:4 structured-sparsity pattern; an unmodified dense checkpoint gets the dense figure, not the marketing headline.",
    "Being superseded by Blackwell for new large-scale builds, but H100 fleets (PCIe and SXM5 alike) remain the largest installed base — relevant for capacity planning against existing customer infrastructure.",
    "Every vGPU mode needs NVIDIA AI Enterprise and a supported hypervisor (ESXi, certified KVM) — MIG alone (bare metal or passthrough) does not. NVAIE licenses the physical GPU, not the slice: partitioning it into 7 MIG instances still licenses as 1 GPU.",
    "Below the 4 GB isolated floor, only software sharing applies (MPS ≤48 clients, Kubernetes GPU-Operator time-slicing, HAMi/KAI fractional, many models per Triton/vLLM serving process) — none of it is hardware memory- or fault-isolated. This is uniform across every GPU on this page, so it isn't broken out per-part here.",
  ],
  sources: [
    { id: "N-H100", label: "NVIDIA — H100 Tensor Core GPU product page / datasheet", url: "https://www.nvidia.com/en-us/data-center/h100/" },
    { id: "N-VGPU-H100", label: "NVIDIA AI Enterprise 8.2 — Hopper H100 vGPU reference", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/hopper-h100.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public H100 datasheet and widely-published PCIe specifications (Sep 2026). Virtualization/licensing figures from NVIDIA AI Enterprise 8.2's Hopper H100 vGPU reference (Sep 2026) — high-confidence, well-established figures. Still verify against nvidia.com and docs.nvidia.com before quoting in a bid.",
};

export const NVIDIA_RTX_PRO_6000: AcceleratorDetail = {
  id: "nvidia-rtx-pro-6000",
  name: "NVIDIA RTX PRO 6000 Blackwell",
  codeName: "Blackwell (GB202), TSMC 4N — Workstation Edition",
  tagline: "96 GB GDDR7 workstation/inference card — Intel's closest direct comparison point",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — launched 2025",
  overview: [
    "NVIDIA's Blackwell-generation professional/workstation card — the natural competitive benchmark for Intel's Arc Pro B60/B70 (this app already cross-references it there: B70 is quoted at ~85% of this card's batch-32 throughput on Llama 3.1 8B). Unlike the data-centre Blackwell parts (B200/GB200/GB300), this is a PCIe add-in card usable in a standard workstation or server chassis, with no NVLink.",
    "5th-generation Tensor Cores add native FP4 support at the workstation tier — 24,064 CUDA cores, 752 Tensor Cores, 188 RT Cores, 96 GB of GDDR7 on a 512-bit bus.",
  ],
  hwSpecs: [
    { label: "Architecture", value: "Blackwell (GB202), TSMC 4N" },
    { label: "CUDA cores", value: "24,064" },
    { label: "Tensor Cores (5th gen)", value: "752" },
    { label: "RT Cores (4th gen)", value: "188" },
    { label: "Form factor", value: "Dual-slot PCIe (Workstation Edition); single-slot Server Edition also available" },
    { label: "Host interface", value: "PCIe Gen5 x16" },
    { label: "Power connector", value: "1× 16-pin (12V-2×6)" },
    { label: "Board power (TDP)", value: "600 W" },
  ],
  memorySpecs: [
    { label: "Memory type", value: "GDDR7, ECC" },
    { label: "Capacity", value: "96 GB" },
    { label: "Bus width", value: "512-bit" },
    { label: "Memory bandwidth", value: "1.79 TB/s (1,792 GB/s)" },
  ],
  tflops: [
    { dataType: "FP64", value: "1.97 TFLOPS" },
    { dataType: "FP32", value: "126 TFLOPS" },
    { dataType: "FP16 / BF16 Tensor Core", value: "503.8 TFLOPS", note: "with sparsity — 251.9 TFLOPS dense" },
    { dataType: "FP8 Tensor Core", value: "1,007.6 TFLOPS", note: "with sparsity — 503.8 TFLOPS dense" },
    { dataType: "FP4 Tensor Core", value: "~4,000 TOPS", note: "with sparsity, NVIDIA's rounded headline figure — dense ≈2,000 TOPS" },
  ],
  swStack: [
    { layer: "Driver / runtime", component: "NVIDIA driver + CUDA runtime", role: "Same CUDA stack as the datacenter parts" },
    { layer: "Kernel libraries", component: "cuDNN, cuBLAS, CUTLASS", role: "GEMM, conv, attention primitives" },
    { layer: "Compiler / DSL", component: "Triton, TensorRT-LLM", role: "Custom kernels; optimized LLM serving path" },
    { layer: "Framework", component: "PyTorch (native CUDA backend)", role: "First-class support" },
    { layer: "LLM serving", component: "vLLM, TensorRT-LLM", role: "Paged attention, continuous batching — same ecosystem as H100/B200" },
    { layer: "Workstation", component: "NVIDIA RTX / Studio drivers", role: "Also a full graphics/creative-workflow GPU, unlike the datacenter-only Blackwell parts" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "None — no NVLink on this card; all peer traffic rides PCIe" },
    { label: "PCIe 5.0 x16 per direction", value: "≈63 GB/s (32 GT/s × 16 lanes × encoding ÷ 8)" },
    { label: "Multi-Instance GPU", value: "Not listed for the Workstation Edition — see Server Edition (4× MIG @ 24 GB) below" },
    { label: "Scaling guidance", value: "Prefer replicas (1 model/GPU) or PP=2; TP across PCIe switches is workable for ≤4 GPUs on one switch" },
  ],
  caveats: [
    "No NVLink — PCIe Gen5 x16 is the only interconnect, same constraint this app already flags for Intel's B60/B70 when comparing multi-card scaling.",
    "FP4 Tensor Core figure is NVIDIA's rounded \"~4,000 TOPS\" marketing headline; the precise dense/sparse split is derived from the FP8 figure's doubling pattern, not an NVIDIA-published exact number — treat as directionally correct.",
    "A Server Edition (single-slot, blower cooler, same silicon) exists for higher-density GPU nodes — see NVIDIA_RTX_PRO_6000_SERVER_EDITION on this page, which carries its own product-page-sourced bandwidth figure (1,597 GB/s) that differs slightly from this Workstation Edition figure (1,792 GB/s); NVIDIA does not publish which convention explains the gap, so don't average or interchange the two.",
  ],
  hostRecommendation: xeon6HostRows(96, 1536, 12),
  sources: [
    { id: "N2", label: "NVIDIA — RTX PRO 6000 Blackwell Server Edition product page (spec table)", url: "https://www.nvidia.com/en-us/data-center/rtx-pro-6000-blackwell-server-edition/" },
    { id: "L1", label: "Lenovo Press LP2264 — ThinkSystem SR680a V4 Product Guide (Xeon 6 lane/host-sizing table)", url: "https://lenovopress.lenovo.com/lp2264-thinksystem-sr680a-v4-server" },
  ],
  sourceNote: "Compiled from NVIDIA's public RTX PRO 6000 Blackwell Workstation Edition datasheet and product pages (Sep 2026). Re-verify against nvidia.com before using in a bid or business case.",
};

export const NVIDIA_GB200_NVL72: AcceleratorDetail = {
  id: "nvidia-gb200-nvl72",
  name: "NVIDIA GB200 NVL72",
  codeName: "Grace Blackwell Superchip — Blackwell (B200) + Grace CPU",
  tagline: "Rack-scale superchip: 2 Blackwell GPUs + 1 Grace CPU, NVLink-fused into a 72-GPU rack",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — general availability since 2025",
  overview: [
    "Unlike every other card on this page, the GB200 is not a single discrete GPU — it's a Superchip: one Grace CPU (72 Arm Neoverse V2 cores) coherently fused via NVLink-C2C to two Blackwell B200 GPUs on one module. 18 of these Superchips (36 Grace CPUs + 72 B200 GPUs) are NVLink-switched together into one GB200 NVL72 rack, which NVIDIA sells and benchmarks as a single unit — the specs below give both the per-GPU/per-Superchip figures and the full-rack aggregate.",
    "This is the current-generation Blackwell platform aimed at the largest training and inference workloads; GB300 NVL72 (also on this page) is the follow-on Blackwell Ultra refresh with more HBM3e capacity and higher FP4 throughput on the same rack architecture.",
  ],
  hwSpecs: [
    { label: "Configuration", value: "36 Grace CPUs + 72 Blackwell B200 GPUs per NVL72 rack" },
    { label: "Grace CPU", value: "72 Arm Neoverse V2 cores per CPU (2,592 cores/rack)" },
    { label: "GPU-CPU link", value: "NVLink-C2C — coherent, chip-to-chip" },
    { label: "NVLink (GPU domain)", value: "5th gen, 1.8 TB/s per GPU · 3.6 TB/s per Superchip · 130 TB/s aggregate per rack" },
    { label: "Cooling", value: "Fully liquid-cooled" },
    { label: "Rack power", value: "~120 kW (approximate — verify against NVIDIA's current datasheet)" },
    { label: "Networking", value: "ConnectX-7 / BlueField-3, ~400 Gb/s per GPU (typical config)" },
  ],
  memorySpecs: [
    { label: "GPU memory type", value: "HBM3e" },
    { label: "GPU memory — per GPU", value: "186 GB @ 8 TB/s" },
    { label: "GPU memory — per Superchip (2 GPUs)", value: "372 GB @ 16 TB/s combined" },
    { label: "GPU memory — full rack (72 GPUs)", value: "13.4 TB @ up to 576 TB/s aggregate" },
    { label: "CPU memory (Grace, LPDDR5X)", value: "Up to 480 GB per Superchip · 17 TB @ 14 TB/s across the rack" },
  ],
  tflops: [
    { dataType: "FP64 / FP64 Tensor Core — per GPU", value: "40 TFLOPS", note: "80 TFLOPS per Superchip (2 GPUs) · 2,880 TFLOPS per rack" },
    { dataType: "FP16 / BF16 Tensor Core — per GPU", value: "5 PFLOPS", note: "with sparsity — 360 PFLOPS aggregate per rack" },
    { dataType: "FP8 / FP6 Tensor Core — per GPU", value: "10 PFLOPS", note: "with sparsity — 720 PFLOPS aggregate per rack" },
    { dataType: "FP4 (NVFP4) Tensor Core — per GPU", value: "20 PFLOPS", note: "with sparsity — 1,440 PFLOPS aggregate per rack (NVIDIA's headline NVL72 figure)" },
  ],
  swStack: [
    { layer: "Driver / runtime", component: "NVIDIA driver + CUDA runtime", role: "Same CUDA stack as H100/RTX PRO 6000 — no new programming model" },
    { layer: "CPU", component: "Grace (Arm Neoverse V2)", role: "Coherent host CPU — not x86; check OS/toolchain Arm support for your stack" },
    { layer: "Kernel libraries", component: "cuDNN, cuBLAS, CUTLASS", role: "GEMM, conv, attention primitives, Blackwell-tuned" },
    { layer: "Collectives", component: "NCCL", role: "NVLink-switch aware — the whole NVL72 domain acts as one large all-to-all fabric" },
    { layer: "LLM serving", component: "TensorRT-LLM, vLLM, Dynamo", role: "Disaggregated prefill/decode across the rack; NVIDIA Dynamo targets this platform specifically" },
    { layer: "Orchestration", component: "NVIDIA Mission Control, Kubernetes + GPU Operator", role: "Rack-scale job scheduling and health management" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "5th-gen NVLink, 1.8 TB/s per GPU · 3.6 TB/s per Superchip · 130 TB/s aggregate per rack" },
    { label: "GPU-to-CPU link", value: "NVLink-C2C — coherent, chip-to-chip (not PCIe)" },
    { label: "Networking", value: "ConnectX-7 / BlueField-3, ~400 Gb/s per GPU (typical config)" },
  ],
  hostRecommendation: [
    { label: "Host CPU", value: "N/A — Grace (Arm Neoverse V2) is the coherent on-module host; there is no Xeon socket to pair" },
  ],
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Not supported — bare metal only" },
    { label: "MIG (hardware partitions)", value: "Supported — ~1g.23gb per GPU, up to 7 instances; disables NVLink P2P on that GPU while active" },
    { label: "MIG-backed vGPU", value: "Not supported (bare metal only)" },
    { label: "Time-sliced vGPU (compute)", value: "Not supported — NVIDIA's Blackwell reference shows this class exposes only a full-GPU time-sliced profile, not applicable bare-metal" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Not supported" },
    { label: "Smallest isolated (memory-fenced) unit", value: "23 GB" },
    { label: "Max isolated MIG slots / GPU", value: "7" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "~95.7%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Per physical GPU — same per-GPU metric as every other part on this page, despite the rack-scale packaging" },
  ],
  caveats: [
    "Sold and racked as a unit — per-GPU/per-Superchip figures above are derived (rack ÷ 72 or ÷ 36) for sizing comparability against single-GPU parts; NVIDIA's own marketing leads with the full-rack numbers.",
    "Grace is Arm (Neoverse V2), not x86 — confirm OS, driver, and any CPU-side software dependencies support Arm before counting on this platform for a bid.",
    "Rack power and per-GPU networking bandwidth are commonly-cited approximate figures, not confirmed against a specific NVIDIA datasheet revision — re-verify before a bid.",
    "GB300 NVL72 (Blackwell Ultra) is the direct successor on the same rack architecture — see that entry for the generational delta.",
    "The ~23 GB MIG profile is extrapolated from the x86-hosted HGX B200 reference, not vendor-confirmed for the NVL72 rack packaging specifically — verify with `nvidia-smi mig -lgip` on an actual tray before quoting it. NVIDIA's support matrix (release 7.0) confirms bare-metal-only deployment for this class; MIG and NVLink-fused tensor-parallel use are per-GPU either/or, never both at once.",
    "Software-level sharing (Kubernetes GPU-Operator time-slicing, MPS ≤48 clients, HAMi/KAI fractional — though HAMi on Grace/Arm hosts is itself unconfirmed) works on top of bare metal here too, same as every other GPU on this page — none of it is hardware-isolated.",
  ],
  sources: [
    { id: "N-VGPU-BW", label: "NVIDIA AI Enterprise 8.2 — Blackwell vGPU reference (MIG/vGPU types)", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/blackwell.html" },
    { id: "N-SUPPORT-7", label: "NVIDIA AI Enterprise 7.0 support matrix (GB200 bare-metal-only)", url: "https://docs.nvidia.com/ai-enterprise/release-7/7.0/support/support-matrix.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public GB200 NVL72 product page and datasheet (Sep 2026). Per-GPU/per-Superchip figures are derived from NVIDIA's published rack totals. Virtualization figures from NVIDIA AI Enterprise 8.2's Blackwell vGPU reference and the 7.0 support matrix — the MIG profile size is extrapolated, not vendor-confirmed for this exact SKU. Re-verify against nvidia.com and docs.nvidia.com before using in a bid or business case.",
};

export const NVIDIA_GB300_NVL72: AcceleratorDetail = {
  id: "nvidia-gb300-nvl72",
  name: "NVIDIA GB300 NVL72",
  codeName: "Grace Blackwell Ultra Superchip — Blackwell Ultra (B300) + Grace CPU",
  tagline: "Blackwell Ultra refresh of GB200 NVL72 — 50% more HBM3e per GPU, faster networking",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — rolling out through 2026",
  overview: [
    "The Blackwell Ultra refresh of GB200 NVL72, on the same rack architecture: 36 Grace CPUs + 72 Blackwell Ultra (B300) GPUs, NVLink-switched into one NVL72 domain. The generational upgrade is capacity- and inference-focused — 288 GB HBM3e per GPU (up from 186 GB on GB200, a ~55% increase) at the same 8 TB/s per-GPU bandwidth, plus faster per-GPU networking via ConnectX-8 SuperNICs.",
    "Third-party reporting on GB300's headline FP4 PFLOPS figure is inconsistent — some sources quote the same 1,440 PFLOPS/rack \"with sparsity\" headline as GB200, others cite 1,440 sparse / 1,080 dense (vs. GB200's 1,440 sparse / 720 dense), which is where the commonly-cited \"1.5× more FP4 compute\" generational claim comes from. Both figures are given below — confirm which convention your source is using before comparing across generations.",
  ],
  hwSpecs: [
    { label: "Configuration", value: "36 Grace CPUs + 72 Blackwell Ultra (B300) GPUs per NVL72 rack" },
    { label: "Grace CPU", value: "72 Arm Neoverse V2 cores per CPU @ 3.1 GHz base (2,592 cores/rack)" },
    { label: "GPU-CPU link", value: "NVLink-C2C — coherent, chip-to-chip" },
    { label: "NVLink (GPU domain)", value: "5th gen, 1.8 TB/s per GPU · 130 TB/s aggregate per rack" },
    { label: "Cooling", value: "Fully liquid-cooled" },
    { label: "Rack power", value: "~120 kW" },
    { label: "Networking", value: "ConnectX-8 SuperNIC, ~800 Gb/s per GPU — 2× GB200's ConnectX-7 per-GPU bandwidth" },
  ],
  memorySpecs: [
    { label: "GPU memory type", value: "HBM3e" },
    { label: "GPU memory — per GPU", value: "288 GB @ 8 TB/s (vs. 186 GB on GB200 — same bandwidth, more capacity)" },
    { label: "GPU memory — full rack (72 GPUs)", value: "20.7 TB @ up to 576 TB/s aggregate" },
    { label: "CPU memory (Grace, LPDDR5X)", value: "17 TB @ 14 TB/s across the rack (unchanged from GB200 — same Grace CPU)" },
  ],
  tflops: [
    { dataType: "FP16 / BF16 Tensor Core — per GPU", value: "5 PFLOPS", note: "with sparsity — 360 PFLOPS aggregate per rack (same as GB200)" },
    { dataType: "FP8 / FP6 Tensor Core — per GPU", value: "10 PFLOPS", note: "with sparsity — 720 PFLOPS aggregate per rack (same as GB200)" },
    { dataType: "FP4 (NVFP4) Tensor Core — per GPU", value: "20 PFLOPS", note: "with sparsity (1,440 PFLOPS/rack) — 15 PFLOPS dense per GPU (1,080 PFLOPS/rack); the dense figure is 1.5× GB200's 720 PFLOPS/rack dense" },
  ],
  swStack: [
    { layer: "Driver / runtime", component: "NVIDIA driver + CUDA runtime", role: "Same CUDA stack as GB200/H100/RTX PRO 6000" },
    { layer: "CPU", component: "Grace (Arm Neoverse V2)", role: "Coherent host CPU — not x86, unchanged from GB200" },
    { layer: "Kernel libraries", component: "cuDNN, cuBLAS, CUTLASS", role: "GEMM, conv, attention primitives, Blackwell Ultra-tuned" },
    { layer: "Collectives", component: "NCCL", role: "NVLink-switch aware across the NVL72 domain" },
    { layer: "LLM serving", component: "TensorRT-LLM, vLLM, Dynamo", role: "Disaggregated prefill/decode — larger per-GPU KV-cache headroom than GB200 from the extra HBM3e" },
    { layer: "Orchestration", component: "NVIDIA Mission Control, Kubernetes + GPU Operator", role: "Rack-scale job scheduling and health management" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "5th-gen NVLink, 1.8 TB/s per GPU · 130 TB/s aggregate per rack (unchanged from GB200)" },
    { label: "GPU-to-CPU link", value: "NVLink-C2C — coherent, chip-to-chip (not PCIe)" },
    { label: "Networking", value: "ConnectX-8 SuperNIC, ~800 Gb/s per GPU — 2× GB200's ConnectX-7 per-GPU bandwidth" },
  ],
  hostRecommendation: [
    { label: "Host CPU", value: "N/A — Grace (Arm Neoverse V2) is the coherent on-module host; there is no Xeon socket to pair" },
  ],
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Not supported — bare metal only (expected)" },
    { label: "MIG (hardware partitions)", value: "Supported — ~1g.34gb per GPU, up to 7 instances; disables NVLink P2P on that GPU while active" },
    { label: "MIG-backed vGPU", value: "Not supported (bare metal only)" },
    { label: "Time-sliced vGPU (compute)", value: "Not supported — bare-metal-only assumed from GB200; unconfirmed for this generation specifically" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Not supported" },
    { label: "Smallest isolated (memory-fenced) unit", value: "34 GB" },
    { label: "Max isolated MIG slots / GPU", value: "7" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "~97.1%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Per physical GPU — same per-GPU metric as every other part on this page, despite the rack-scale packaging" },
  ],
  caveats: [
    "FP4 PFLOPS headline figures conflict across third-party sources for this generation specifically — see the overview note. Confirm the source convention (dense vs. sparse) before quoting a comparison against GB200 in a bid.",
    "Sold and racked as a unit — per-GPU figures above are derived from NVIDIA's published rack totals, same caveat as GB200.",
    "Grace is Arm (Neoverse V2), not x86 — same OS/toolchain consideration as GB200.",
    "FP64 throughput is not confidently sourced for this generation — Blackwell Ultra's stated focus is FP4/inference capacity, not FP64/HPC uplift, so treat it as roughly GB200-class until confirmed rather than assuming an improvement.",
    "The ~34 GB MIG profile is extrapolated from the x86-hosted HGX B300 reference, not vendor-confirmed for the NVL72 rack packaging — verify with `nvidia-smi mig -lgip` before quoting it. Whether vGPU (any mode) is supported at all on this generation is itself an open question with NVIDIA, not just the profile size.",
    "Software-level sharing (Kubernetes GPU-Operator time-slicing, MPS ≤48 clients, HAMi/KAI fractional — HAMi on Grace/Arm hosts is unconfirmed) works on top of bare metal here too, same as every other GPU on this page — none of it is hardware-isolated.",
  ],
  sources: [
    { id: "N-VGPU-BW", label: "NVIDIA AI Enterprise 8.2 — Blackwell vGPU reference (MIG/vGPU types)", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/blackwell.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public GB300 NVL72 product materials and third-party technical reporting (Sep 2026) — the FP4 dense/sparse split and rack power are less consistently reported for this generation than GB200's. Virtualization figures are extrapolated from the HGX B300 vGPU reference and carry more uncertainty than GB200's (see caveats). Re-verify against nvidia.com and docs.nvidia.com before using in a bid or business case.",
};

export const NVIDIA_B200_HGX: AcceleratorDetail = {
  id: "nvidia-b200-hgx",
  name: "NVIDIA HGX B200",
  codeName: "Blackwell (B200), SXM6, TSMC 4N — x86-hosted 8-GPU baseboard",
  tagline: "The x86-hosted Blackwell part — same silicon as GB200, no Grace CPU required",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — high-end, prior generation, still orderable",
  overview: [
    "The balanced Blackwell part for a conventional x86-hosted server: same FP8/BF16 throughput as B300, two-thirds of B300's dense FP4, 180 GB HBM3e, but 30× B300's FP64 and 24× its INT8. For mixed AI + HPC estates, or where 1,000 W vs. 1,100 W per GPU decides air-cooling feasibility, B200 is the safer high-end choice — and unlike GB200/GB300 NVL72, it drops into a standard Xeon-hosted HGX chassis rather than requiring NVIDIA's Grace CPU.",
    "Sold as an 8-GPU HGX baseboard (SXM6 modules), not a single card — the specs below are per-GPU unless stated otherwise. OEM end-of-sale risk is real as B300/Rubin ramp (Dell's XE9780L, for example, lists B200 support only on that specific chassis).",
  ],
  hwSpecs: [
    { label: "GPU architecture", value: "NVIDIA Blackwell" },
    { label: "Form factor", value: "SXM6; 8 GPUs on HGX B200 baseboard" },
    { label: "GPU TDP", value: "1,000 W (8.0 kW per baseboard of GPU silicon)" },
    { label: "NVLink", value: "5th gen, 1.8 TB/s per GPU; 14.4 TB/s total" },
    { label: "Scale-out networking", value: "0.8 TB/s per HGX (8 × 400 Gb/s via host PCIe NICs — no integrated CX-8)" },
    { label: "Host interface", value: "PCIe Gen5 (x86-hosted, no Grace CPU required)" },
  ],
  memorySpecs: [
    { label: "Memory type", value: "HBM3e" },
    { label: "Capacity per GPU", value: "180 GB (Dell/Supermicro) — NVIDIA's own HGX table implies 175 GB (1.4 TB ÷ 8); plan on 180 GB" },
    { label: "Memory bandwidth", value: "~8 TB/s per GPU (not on NVIDIA's own HGX spec table — widely-cited third-party figure)" },
    { label: "HGX aggregate", value: "1.4 TB across the 8-GPU baseboard" },
  ],
  interconnect: [
    { label: "GPU-to-GPU", value: "NVLink 5, 1.8 TB/s per GPU" },
    { label: "GPU-to-NIC", value: "Host PCIe Gen5 x16 (≈63 GB/s/dir) → 400G per GPU at line rate; 800G NICs do not fit in Gen5 x16" },
    { label: "Scaling guidance", value: "TP=8 within the node; 400G ConnectX-7 per GPU for scale-out" },
  ],
  tflops: [
    { dataType: "FP4 Tensor", value: "18,000 TFLOPS", note: "with sparsity — 9,000 TFLOPS dense (HGX total 144 PFLOPS sparse ÷ 8)" },
    { dataType: "FP8 / FP6 Tensor", value: "9,000 TFLOPS", note: "with sparsity — 4,500 TFLOPS dense" },
    { dataType: "INT8 Tensor", value: "9,000 TOPS", note: "with sparsity — 4,500 TOPS dense (HGX total 72 POPS ÷ 8)" },
    { dataType: "FP16 / BF16 Tensor", value: "4,500 TFLOPS", note: "with sparsity — 2,250 TFLOPS dense" },
    { dataType: "TF32 Tensor", value: "2,250 TFLOPS", note: "with sparsity — 1,125 TFLOPS dense" },
    { dataType: "FP32 (CUDA)", value: "75 TFLOPS", note: "dense" },
    { dataType: "FP64 / FP64 Tensor", value: "37 TFLOPS", note: "dense (HGX total 296 TFLOPS ÷ 8)" },
  ],
  swStack: [
    { layer: "Driver / runtime", component: "NVIDIA driver + CUDA runtime", role: "Same CUDA stack as every other part on this page" },
    { layer: "Inference / training", component: "TensorRT-LLM, NeMo, vLLM, SGLang, NIM", role: "Same mature serving stack as H100/RTX PRO 6000" },
    { layer: "HPC", component: "Full FP64 Tensor Core (37 TFLOPS/GPU)", role: "The one Blackwell datacentre part on this page with genuine HPC-class FP64 headroom" },
  ],
  hostRecommendation: xeon6HostRows(180, 2880, 23),
  caveats: [
    "HBM capacity has a genuine cross-source conflict: Dell and Supermicro spec sheets say 180 GB/GPU; NVIDIA's own HGX table implies 175 GB (1.4 TB ÷ 8 GPUs). Plan on 180 GB but flag the discrepancy if precision matters.",
    "Per-GPU memory bandwidth (~8 TB/s) is not on NVIDIA's own HGX spec table — it's a widely-cited third-party figure, not a first-party one. Cross-check before a bid.",
    "OEM end-of-sale risk: as B300/Rubin ramp, some OEMs are narrowing B200 availability to specific chassis (e.g. Dell XE9780L only) — confirm current OEM roadmap before quoting a procurement window.",
    "This is the x86-hosted HGX baseboard, not the Grace-attached GB200/GB300 NVL72 rack-scale Superchip also on this page — same B200 silicon, very different platform (Xeon-hostable here vs. Grace-only there).",
  ],
  sources: [
    { id: "N3", label: "NVIDIA — HGX platform page, HGX B300 / B200 specification table", url: "https://www.nvidia.com/en-us/data-center/hgx/" },
    { id: "D1", label: "Dell — PowerEdge XE series AI spec sheet (Rev A07)", url: "https://www.delltechnologies.com/asset/en-us/products/servers/technical-support/poweredge-xe-ai-spec-sheet.pdf" },
    { id: "S2", label: "Supermicro — SYS-822GS-NBRT datasheet (HGX B200)", url: "https://www.supermicro.com/en/products/system/datasheet/sys-822gs-nbrt" },
    { id: "L1", label: "Lenovo Press LP2264 — ThinkSystem SR680a V4 Product Guide (Xeon 6 lane/host-sizing table)", url: "https://lenovopress.lenovo.com/lp2264-thinksystem-sr680a-v4-server" },
  ],
  sourceNote: "Compiled from NVIDIA's public HGX platform page and OEM (Dell, Supermicro, Lenovo) spec sheets (Sep 2026). Re-verify against nvidia.com before using in a bid or business case.",
};

export const NVIDIA_H200_NVL: AcceleratorDetail = {
  id: "nvidia-h200-nvl",
  name: "NVIDIA H200 NVL",
  codeName: "Hopper (GH100), same die as H100/H200 SXM — PCIe with NVLink bridges",
  tagline: "The only mid-tier PCIe card with HBM and an NVLink fabric",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — previous-generation Hopper silicon",
  overview: [
    "The only mid-tier PCIe part with HBM and an NVLink fabric: 141 GB HBM3e at 4.8 TB/s — 3× the RTX PRO 6000's bandwidth — plus 2- or 4-way NVLink bridges at 900 GB/s, bundled with a 5-year NVIDIA AI Enterprise subscription. It's previous-generation Hopper silicon, though: no FP4, and dense FP8 roughly equal to an RTX PRO 6000.",
    "Read before quoting a number: several spec aggregators print H200 SXM figures against the NVL card. The NVL's compute is lower than SXM (600 W vs. 700 W clocks) — the figures below use the NVL column specifically.",
  ],
  hwSpecs: [
    { label: "GPU architecture", value: "NVIDIA Hopper (GH100) — same die as H100/H200 SXM" },
    { label: "Max TDP", value: "Up to 600 W, configurable down to 450 W" },
    { label: "Form factor", value: "PCIe dual-slot, air-cooled" },
    { label: "Host interface", value: "PCIe Gen5, 128 GB/s bidirectional" },
    { label: "NVLink bridge", value: "2-way or 4-way, 900 GB/s (HPE S4A90C 2-way / S4A91C 4-way)" },
    { label: "Multi-Instance GPU", value: "Up to 7 MIG instances @ 18 GB (1g.18gb) — supersedes an earlier reseller-reported 16.5 GB figure" },
    { label: "Decoders", value: "7× NVDEC, 7× JPEG — no NVENC" },
    { label: "NVIDIA AI Enterprise", value: "Included — 5-year subscription (a real TCO difference vs. RTX PRO 6000, which licenses it separately)" },
    { label: "Claimed uplift vs. H100 NVL", value: "Up to 1.7× LLM inference, 1.3× HPC (NVIDIA claim)" },
  ],
  memorySpecs: [
    { label: "Capacity", value: "141 GB HBM3e" },
    { label: "Peak bandwidth", value: "4.8 TB/s" },
    { label: "4-way NVLink domain", value: "564 GB pooled (4 × 141 GB) at 900 GB/s GPU-GPU" },
    { label: "vs. RTX PRO 6000", value: "1.47× capacity, 3.0× bandwidth" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "NVLink bridge, 900 GB/s, in 2- or 4-GPU islands" },
    { label: "8-GPU node topology", value: "Two 4-way NVLink islands; inter-island traffic rides PCIe" },
    { label: "PCIe 5.0 x16 per direction", value: "≈63 GB/s" },
    { label: "Scaling guidance", value: "TP=4 inside an island; use pipeline-parallel or replicas across islands" },
  ],
  tflops: [
    { dataType: "FP4 Tensor", value: "Not published", note: "Hopper has no FP4 — weight-only FP4 needs software dequantization" },
    { dataType: "FP8 Tensor", value: "3,341 TFLOPS", note: "with sparsity (NVIDIA SC24 datasheet) — 1,670.5 TFLOPS dense; Lenovo LP1944 lists 1,570 dense, ~6% below half of 3,341" },
    { dataType: "INT8 Tensor", value: "3,341 TOPS", note: "with sparsity — 1,670.5 TOPS dense" },
    { dataType: "FP16 / BF16 Tensor", value: "1,671 TFLOPS", note: "with sparsity — 835.5 TFLOPS dense" },
    { dataType: "TF32 Tensor", value: "835 TFLOPS", note: "with sparsity (derived: half of BF16 sparse on the Hopper ladder) — 417.5 TFLOPS dense" },
    { dataType: "FP32 (CUDA)", value: "60 TFLOPS", note: "dense — SXM variant publishes 67" },
    { dataType: "FP64 Tensor", value: "60 TFLOPS", note: "dense — genuine HPC-capable FP64" },
    { dataType: "FP64 (CUDA)", value: "30 TFLOPS", note: "dense" },
  ],
  swStack: [
    { layer: "Inference", component: "TensorRT-LLM, vLLM, SGLang, Triton, NIM (FP8)", role: "Same mature Hopper-generation serving stack as H100" },
    { layer: "HPC", component: "Full FP64 Tensor Core; CUDA-X HPC", role: "Genuine HPC-capable FP64, unlike the RTX PRO line" },
    { layer: "NVIDIA AI Enterprise", component: "Included, 5-year subscription", role: "Bundled licensing — a real TCO difference vs. RTX PRO 6000" },
  ],
  hostRecommendation: xeon6HostRows(141, 2256, 18),
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Supported" },
    { label: "MIG (hardware partitions)", value: "Supported — 1g.18gb smallest profile, up to 7 instances/GPU" },
    { label: "MIG-backed vGPU", value: "Supported — 18 GB min, up to 7/GPU" },
    { label: "vGPU time-sliced inside a MIG slice", value: "Not supported" },
    { label: "Time-sliced vGPU (compute, C-series)", value: "Supported — 4 GB min, up to 32/GPU (or 4 GB × 16 in mixed-size mode)" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Not supported" },
    { label: "Smallest isolated (memory-fenced) unit", value: "4 GB" },
    { label: "Max isolated slots / GPU", value: "32 (256 across an 8-GPU node)" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "75%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Bundled — 5-year subscription included with the GPU (elsewhere on this page it's $4,500/GPU/yr standalone list)" },
  ],
  caveats: [
    "NVL compute figures vs. SXM: several spec aggregators print H100/H200 SXM numbers against the NVL card by mistake — the figures above are specifically the NVL column, citing NVIDIA's SC24 datasheet.",
    "Previous-generation Hopper silicon with real supply/EOL risk as OEMs prioritize Blackwell — check the current OEM roadmap before a bid.",
    "No FP4 — Hopper's Tensor Cores stop at FP8; don't compare directly against Blackwell parts' FP4 throughput without noting this.",
    "The MIG slice size was previously reported as 16.5 GB (reseller datasheet) — NVIDIA's own AI Enterprise 8.2 vGPU reference corrects this to 18 GB (1g.18gb × 7), which is what's used above.",
    "Software-level sharing (Kubernetes GPU-Operator time-slicing, MPS ≤48 clients, HAMi/KAI fractional, many models per Triton/vLLM process) works here too, same as every other GPU on this page — none of it is hardware-isolated.",
  ],
  sources: [
    { id: "N5", label: "NVIDIA — H200 product page (H200 NVL positioning, 5-yr NVAIE)", url: "https://www.nvidia.com/en-us/data-center/h200/" },
    { id: "N6", label: "NVIDIA/PNY — H200 NVL datasheet (Aug 2024)", url: "https://www.pny.com/file%20library/company/support/linecards/data-center-gpus/h200-nvl-datasheet.pdf" },
    { id: "L4", label: "Lenovo Press LP1944 — ThinkSystem NVIDIA H200 141GB GPUs Product Guide", url: "https://lenovopress.lenovo.com/lp1944-nvidia-h200-141gb-gpu" },
    { id: "L1", label: "Lenovo Press LP2264 — ThinkSystem SR680a V4 Product Guide (Xeon 6 lane/host-sizing table)", url: "https://lenovopress.lenovo.com/lp2264-thinksystem-sr680a-v4-server" },
    { id: "P1", label: "GPUpoet — H200 NVL card page citing NVIDIA's SC24 datasheet", url: "https://gpupoet.com/gpu/learn/card/nvidia-h200-nvl" },
    { id: "P2", label: "Hydra Host / Symmatrix — H200 NVL spec listings", url: "https://hydrahost.com/nvidia/h200/" },
    { id: "N-VGPU-H200", label: "NVIDIA AI Enterprise 8.2 — Hopper H200 vGPU reference", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/hopper-h200.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public H200 NVL datasheet, NVIDIA's H200 product page, and Lenovo Press product guides (Sep 2026). Virtualization/licensing figures from NVIDIA AI Enterprise 8.2's Hopper H200 vGPU reference (Sep 2026). Re-verify against nvidia.com and docs.nvidia.com before using in a bid or business case.",
};

export const NVIDIA_L4: AcceleratorDetail = {
  id: "nvidia-l4",
  name: "NVIDIA L4 Tensor Core GPU",
  codeName: "Ada Lovelace (AD104) — low-profile PCIe",
  tagline: "Slot-powered 72 W single-slot card — video/vision and small-model, not LLM-serving",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — previous generation, still on OEM price lists",
  overview: [
    "The slot-powered 72 W, single-slot low-profile card that drops into any 1U/2U server without an auxiliary power cable. Its 300 GB/s bandwidth makes it a video/vision and small-model part; for new LLM work the RTX PRO 4500 delivers 2.7× the bandwidth at 2.3× the power.",
    "Read before quoting a number: NVIDIA publishes L4 Tensor figures with sparsity and states dense is one-half. No FP4. PCIe Gen4 host link (not Gen5).",
  ],
  hwSpecs: [
    { label: "GPU architecture", value: "NVIDIA Ada Lovelace (AD104)" },
    { label: "Max TDP", value: "72 W — slot-powered, no auxiliary power connector" },
    { label: "Form factor", value: "1-slot, low-profile (HHHL), 169 × 68 mm" },
    { label: "Host interface", value: "PCIe Gen4 x16, 64 GB/s bidirectional" },
    { label: "Clocks", value: "795 MHz base / 2,040 MHz boost" },
    { label: "Media engines", value: "2× NVENC, 4× NVDEC, 4× JPEG; AV1 encode/decode" },
    { label: "Multi-Instance GPU", value: "Not listed by NVIDIA for L4 — assume no MIG; use vGPU time-slicing" },
    { label: "Secure boot", value: "Root of Trust; NEBS Level 3 ready" },
    { label: "Successor", value: "RTX PRO 4500 claims >5× L4 small-model inference throughput" },
  ],
  memorySpecs: [
    { label: "Capacity / type", value: "24 GB GDDR6" },
    { label: "Interface width", value: "192-bit" },
    { label: "Peak bandwidth", value: "300 GB/s" },
    { label: "ECC", value: "On by default" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "None — PCIe Gen4 only, no NVLink bridge" },
    { label: "PCIe 4.0 x16 per direction", value: "≈31.5 GB/s" },
    { label: "Scaling guidance", value: "Replicas only — sharding across Gen4 links is not viable for LLM decode" },
  ],
  tflops: [
    { dataType: "FP4 Tensor", value: "Not published", note: "not supported on Ada" },
    { dataType: "FP8 Tensor", value: "485 TFLOPS", note: "with sparsity — 242.5 TFLOPS dense; 4th-gen Tensor Core, FP8 Transformer Engine" },
    { dataType: "INT8 Tensor", value: "485 TOPS", note: "with sparsity — 242.5 TOPS dense" },
    { dataType: "FP16 / BF16 Tensor", value: "242 TFLOPS", note: "with sparsity — 121 TFLOPS dense" },
    { dataType: "TF32 Tensor", value: "120 TFLOPS", note: "with sparsity — 60 TFLOPS dense" },
    { dataType: "FP32 (CUDA)", value: "30.3 TFLOPS", note: "dense" },
    { dataType: "FP64", value: "Not published", note: "negligible — not an HPC part" },
  ],
  swStack: [
    { layer: "Inference", component: "TensorRT, TensorRT-LLM (FP8), Triton, vLLM, DeepStream", role: "Video/vision-first serving stack" },
    { layer: "Virtualisation", component: "NVIDIA vGPU (vPC/vWS/vCS)", role: "Multi-tenant slicing in the absence of hardware MIG" },
    { layer: "NVIDIA AI Enterprise", component: "Supported, subscription separate", role: "Not bundled — licence on top" },
  ],
  hostRecommendation: xeon6HostRows(24, 384, 3),
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Supported" },
    { label: "MIG (hardware partitions)", value: "Not supported — no MIG on this GPU" },
    { label: "MIG-backed vGPU", value: "Not applicable (no MIG)" },
    { label: "Time-sliced vGPU (compute, C-series)", value: "Supported — 4 GB min, up to 6/GPU (equal-size); 4 GB × 4 in mixed-size mode" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Supported" },
    { label: "Smallest isolated (memory-fenced) unit", value: "4 GB" },
    { label: "Max isolated slots / GPU", value: "6 (48 across an 8-GPU node)" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "75%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Required for vGPU — licensed separately, not bundled with the card" },
  ],
  caveats: [
    "End-of-sale timing varies by OEM — entry-tier L4 SKUs may be withdrawn in favour of RTX PRO 4500 during 2026-27; check current OEM EOL notices before a bid.",
    "No MIG support on this part — the only isolation mechanism below software-level sharing is time-sliced vGPU, at a 4 GB floor.",
    "Video/vision and small-model part, not an LLM-serving workhorse — 300 GB/s bandwidth and no FP4 make it a poor fit for ≥30B-class serving.",
    "An earlier-reported 1 GB smallest-vGPU figure for L4 was a graphics (vPC) profile, not a compute one — NVIDIA's actual compute floor is 4 GB (× 6 per GPU, or × 4 in mixed-size mode).",
    "Software-level sharing (Kubernetes GPU-Operator time-slicing, MPS ≤48 clients, HAMi/KAI fractional, many models per Triton/vLLM process) works here too, same as every other GPU on this page — none of it is hardware-isolated.",
  ],
  sources: [
    { id: "N4", label: "NVIDIA — L4 Tensor Core GPU product page / datasheet", url: "https://www.nvidia.com/en-zz/data-center/l4/" },
    { id: "P5", label: "SourceCode / ITCreations — L4 listings (192-bit bus, clocks, ECC default)", url: "https://store.sourcecode.com/en-us/bg-bucket-compare/124/9757" },
    { id: "L1", label: "Lenovo Press LP2264 — ThinkSystem SR680a V4 Product Guide (Xeon 6 lane/host-sizing table)", url: "https://lenovopress.lenovo.com/lp2264-thinksystem-sr680a-v4-server" },
    { id: "N-VGPU-ADA", label: "NVIDIA AI Enterprise 8.2 — Ada Lovelace vGPU reference", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/ada-lovelace.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public L4 product page/datasheet and third-party reseller listings (Sep 2026). Virtualization/licensing figures from NVIDIA AI Enterprise 8.2's Ada Lovelace vGPU reference (Sep 2026). Re-verify against nvidia.com and docs.nvidia.com before using in a bid or business case.",
};

export const NVIDIA_RTX_PRO_4500: AcceleratorDetail = {
  id: "nvidia-rtx-pro-4500",
  name: "NVIDIA RTX PRO 4500 Blackwell Server Edition",
  codeName: "Blackwell (RTX PRO data-centre variant) — single-slot PCIe",
  tagline: "165 W single-slot successor to the L4 slot — native FP4, not an LLM-serving workhorse",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — announced GTC 2026 (Mar 2026)",
  overview: [
    "The 165 W single-slot successor to the L4 slot: 32 GB of GDDR7 at 800 GB/s with native FP4, fitting mainstream 1U/2U enterprise and edge servers without an auxiliary-cooling redesign. It's a small-model / vision / vector-search part, not an LLM-serving workhorse — 32 GB caps a single card at roughly 30B-class models at FP8.",
    "Read before quoting a number: NVIDIA's RTX PRO spec pages don't state the sparsity convention inline. This reference treats the published Tensor figures as sparse and derives dense = ½, per NVIDIA's RTX PRO datasheet footnotes — verify against the PDF before quoting a dense number.",
  ],
  hwSpecs: [
    { label: "GPU architecture", value: "NVIDIA Blackwell (RTX PRO data-centre variant)" },
    { label: "CUDA cores", value: "10,496" },
    { label: "Tensor Cores", value: "5th generation — adds FP4" },
    { label: "RT Cores", value: "82 (4th generation)" },
    { label: "Board power", value: "Up to 165 W — above the 75 W slot-power limit, needs a 1× PCIe CEM5 16-pin connector" },
    { label: "Host interface", value: "PCIe 5.0 x16" },
    { label: "Form factor", value: "Single-slot FHFL, 4.4\" H × 10.5\" L — full-length; will not fit L4's low-profile slot" },
    { label: "Thermal solution", value: "Passive (server airflow)" },
    { label: "Multi-Instance GPU", value: "Up to 2 instances @ 16 GB" },
    { label: "Media engines", value: "3× NVENC (9th gen), 3× NVDEC (6th gen); AV1, 4:2:2 H.264/HEVC" },
    { label: "OEM uptake", value: "Supermicro RTX PRO BSE portfolio; Compal; Dell XE7740/XE7745; Supermicro SYS-522GA-NRT" },
  ],
  memorySpecs: [
    { label: "Capacity / type", value: "32 GB GDDR7" },
    { label: "Interface width", value: "256-bit" },
    { label: "Peak bandwidth", value: "800 GB/s" },
    { label: "vs. L4", value: "1.33× capacity, 2.67× bandwidth (32 vs. 24 GB; 800 vs. 300 GB/s)" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "None — no NVLink bridge; all peer traffic rides PCIe 5.0" },
    { label: "PCIe 5.0 x16 per direction", value: "≈63 GB/s" },
    { label: "Multi-Instance GPU", value: "2 × 16 GB instances" },
    { label: "Scaling guidance", value: "Replicate, don't shard — TP>2 over PCIe is rarely worth it for models that fit in 32 GB" },
  ],
  tflops: [
    { dataType: "FP4 Tensor", value: "1,600 TFLOPS", note: "with sparsity (published 1.6 PFLOPS) — 800 TFLOPS dense" },
    { dataType: "FP8 Tensor", value: "811 TFLOPS", note: "with sparsity — 405.5 TFLOPS dense" },
    { dataType: "FP16 / BF16 Tensor", value: "406 TFLOPS", note: "with sparsity — 203 TFLOPS dense" },
    { dataType: "TF32 Tensor", value: "203 TFLOPS", note: "with sparsity — 101.5 TFLOPS dense" },
    { dataType: "INT8", value: "Not published", note: "not on the product page" },
    { dataType: "FP32 (CUDA)", value: "51 TFLOPS", note: "dense, non-Tensor" },
    { dataType: "FP64", value: "Not published", note: "RTX-class FP64 is typically 1:64 of FP32 — don't plan HPC on this part" },
    { dataType: "RT Core (peak)", value: "154 TFLOPS", note: "graphics only" },
  ],
  swStack: [
    { layer: "Inference", component: "TensorRT / TensorRT-LLM, Triton, vLLM, NIM microservices (FP4 path)", role: "FP4-native serving path — the headline capability of this generation" },
    { layer: "Vision / video", component: "Metropolis, CV-CUDA, VSS blueprint, Cosmos Reason VLMs", role: "Vision-first workload targeting" },
    { layer: "Data science", component: "CUDA-X (cuDF, cuML), cuVS", role: "Vector search (cuVS/CAGRA) — NVIDIA claims up to 50× vs. CPU-only" },
    { layer: "Virtualisation", component: "vWS / vPC, MIG-backed time-slicing", role: "Multi-tenant isolation via 2 MIG instances" },
  ],
  hostRecommendation: xeon6HostRows(32, 512, 4),
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Supported" },
    { label: "MIG (hardware partitions)", value: "Supported — 1g.16gb smallest profile, up to 2 instances/GPU" },
    { label: "MIG-backed vGPU", value: "Supported — 8 GB min, up to 4/GPU (4 inside a 2g slice, or 2 inside a 1g slice)" },
    { label: "vGPU time-sliced inside a MIG slice", value: "Supported" },
    { label: "Time-sliced vGPU (compute, C-series)", value: "Supported — 8 GB min, up to 4/GPU" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Supported — profiles down to 2 GB, but not usable for compute" },
    { label: "Smallest isolated (memory-fenced) unit", value: "8 GB" },
    { label: "Max isolated slots / GPU", value: "4 (32 across an 8-GPU node)" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "87.5%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Required for all vGPU modes; NVIDIA has offered discounted NVAIE bundling with this card via Lenovo" },
  ],
  caveats: [
    "Sparse-vs-dense convention isn't stated inline on NVIDIA's RTX PRO 4500 spec pages — this reference treats published Tensor figures as sparse (dense = ½), per the datasheet footnote. Halves every dense planning number if misread.",
    "INT8 TOPS and FP64 are not published for this part — classic quantized CV pipelines that size on INT8, or any HPC-FP64 use case, have no first-party number to plan against.",
    "Slot-power vs. card-power conflict at the chassis level: some OEM chassis (e.g. Dell XE7740) list 16 SW slots rated at 75 W, but this card draws 165 W — confirm per-slot power budget on the target chassis before assuming full population.",
    "ECC status is not explicitly stated on the product page, though the RTX PRO family generally ships with ECC — confirm on the datasheet before treating it as an enterprise acceptance criterion.",
    "An earlier-reported 2 GB smallest-vGPU figure for this card was a graphics (vPC) profile, not a compute one — NVIDIA's actual compute floor is 8 GB.",
    "Software-level sharing (Kubernetes GPU-Operator time-slicing, MPS ≤48 clients, HAMi/KAI fractional, many models per Triton/vLLM process) works here too, same as every other GPU on this page — none of it is hardware-isolated.",
  ],
  sources: [
    { id: "N1", label: "NVIDIA — RTX PRO 4500 Blackwell Server Edition product page (spec table)", url: "https://www.nvidia.com/en-us/data-center/rtx-pro-4500-blackwell-server-edition/" },
    { id: "N4", label: "NVIDIA — L4 Tensor Core GPU product page / datasheet (comparison baseline)", url: "https://www.nvidia.com/en-zz/data-center/l4/" },
    { id: "D1", label: "Dell — PowerEdge XE series AI spec sheet (Rev A07)", url: "https://www.delltechnologies.com/asset/en-us/products/servers/technical-support/poweredge-xe-ai-spec-sheet.pdf" },
    { id: "S3", label: "Supermicro — SYS-522GA-NRT datasheet / eStore", url: "https://www.supermicro.com/en/products/system/datasheet/sys-522ga-nrt" },
    { id: "S4", label: "Supermicro — RTX PRO BSE solutions page", url: "https://www.supermicro.com/en/accelerators/nvidia/supermicro-rtx-pro-bse" },
    { id: "X2", label: "Compal — GTC 2026 HGX Rubin NVL8 + RTX PRO 4500 support announcement", url: "https://www.compal.com/en-us/media/314/ren-bao-yu-gtc-2026fa-biao-nvidia-hgx-tm-rubin-gao" },
    { id: "L1", label: "Lenovo Press LP2264 — ThinkSystem SR680a V4 Product Guide (Xeon 6 lane/host-sizing table)", url: "https://lenovopress.lenovo.com/lp2264-thinksystem-sr680a-v4-server" },
    { id: "N-VGPU-BW", label: "NVIDIA AI Enterprise 8.2 — Blackwell vGPU reference (MIG/vGPU types)", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/blackwell.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public RTX PRO 4500 Blackwell Server Edition product page and OEM (Dell, Supermicro, Compal) spec sheets (Sep 2026). Virtualization/licensing figures from NVIDIA AI Enterprise 8.2's Blackwell vGPU reference (Sep 2026). Re-verify against nvidia.com and docs.nvidia.com before using in a bid or business case.",
};

export const NVIDIA_RTX_PRO_6000_SERVER_EDITION: AcceleratorDetail = {
  id: "nvidia-rtx-pro-6000-server-edition",
  name: "NVIDIA RTX PRO 6000 Blackwell Server Edition",
  codeName: "Blackwell (RTX PRO data-centre variant) — dual-slot PCIe",
  tagline: "NVIDIA's L40S successor and enterprise-volume part — 96 GB GDDR7, native FP4, no NVLink",
  accent: NVIDIA_ACCENT,
  accentRgb: NVIDIA_ACCENT_RGB,
  statusBadge: "Shipping — broad OEM availability since Aug 2025",
  overview: [
    "NVIDIA's L40S successor and the enterprise volume part: 96 GB GDDR7 at 1.6 TB/s with native FP4 in an air-cooled 600 W PCIe card that every tier-1 OEM ships in 2-, 4- and 8-GPU chassis. It holds a 70B model at FP8 on one card, but has no NVLink — multi-GPU tensor parallelism rides PCIe.",
    "This is the Server Edition specifically — see NVIDIA_RTX_PRO_6000 on this page for the Workstation Edition, which quotes a slightly different memory-bandwidth figure (1,792 vs. this card's 1,597 GB/s) from its own NVIDIA product page. Same core silicon (24,064 CUDA cores, 752 Tensor Cores, 188 RT cores, 600 W, 96 GB GDDR7), different published bandwidth — don't average or interchange the two without checking both product pages.",
    "Read before quoting a number: Tensor figures follow NVIDIA's RTX PRO convention (with sparsity, dense = ½). The published TF32 figure (234 TFLOPS) is inconsistent with the 2:1 ladder implied by BF16 (1 PFLOP) — treated as published-as-is below. NVIDIA AI Enterprise is NOT bundled with this GPU (unlike H200 NVL).",
  ],
  hwSpecs: [
    { label: "GPU architecture", value: "NVIDIA Blackwell (RTX PRO data-centre variant)" },
    { label: "CUDA cores", value: "24,064" },
    { label: "Tensor Cores", value: "5th generation, 2nd-gen Transformer Engine — adds FP4" },
    { label: "RT Cores", value: "188 (4th generation)" },
    { label: "Max power", value: "Up to 600 W, configurable — Lenovo ships a 450 W slot-capped SKU (feature CHWT) for 4-up in the SR650a V4" },
    { label: "Form factor", value: "Air: dual-slot FHFL · Liquid: single-slot FHXL" },
    { label: "Host interface", value: "PCIe 5.0 x16" },
    { label: "Display", value: "4× DisplayPort 2.1 — usable for OVX/visual workloads" },
    { label: "Media engines", value: "4× NVENC (9th gen), 4× NVDEC (6th gen)" },
    { label: "Multi-Instance GPU", value: "Up to 4 fully isolated instances, ≈24 GB each" },
    { label: "Variants", value: "RTX PRO 6000D 48 GB PCIe (HPE part S6W21C) — regional variant, not modelled here" },
    { label: "OEM availability", value: "Cisco, Dell, HPE, Lenovo, Supermicro 2U mainstream servers; 2/4/8-GPU RTX PRO Server family" },
  ],
  memorySpecs: [
    { label: "Capacity / type", value: "96 GB GDDR7 with ECC" },
    { label: "Interface width", value: "512-bit" },
    { label: "Peak bandwidth", value: "1,597 GB/s" },
    { label: "vs. H200 NVL", value: "0.68× capacity, 0.33× bandwidth — the core mid-tier trade-off" },
  ],
  interconnect: [
    { label: "GPU-to-GPU fabric", value: "None on this SKU — an NVLink bridge is listed as 'optional' in the SYS-522GA-NRT config but applies to other GPUs, not this one" },
    { label: "PCIe 5.0 x16 per direction", value: "≈63 GB/s" },
    { label: "Multi-Instance GPU", value: "4 instances" },
    { label: "Server topology", value: "RTX PRO Server reference: 2-8-5-200 (CPU-GPU-NIC-Gbps); PCIe switch boards; CX-8 SuperNIC with PCIe Gen6 switch options" },
    { label: "Scaling guidance", value: "Prefer replicas (1 model/GPU) or PP=2; TP across PCIe switches is feasible for ≤4 GPUs on one switch — validate all-reduce bandwidth on the target chassis" },
  ],
  tflops: [
    { dataType: "FP4 Tensor", value: "4,000 TFLOPS", note: "with sparsity (published 4 PFLOPS) — 2,000 TFLOPS dense" },
    { dataType: "FP8 Tensor", value: "2,000 TFLOPS", note: "with sparsity (published 2 PFLOPS) — 1,000 TFLOPS dense" },
    { dataType: "FP16 / BF16 Tensor", value: "1,000 TFLOPS", note: "with sparsity (published 1 PFLOP) — 500 TFLOPS dense" },
    { dataType: "TF32 Tensor", value: "234 TFLOPS", note: "convention unclear — inconsistent with the BF16 2:1 ladder; treated as published-as-is" },
    { dataType: "INT8", value: "Not published", note: "not on the product page" },
    { dataType: "FP32 (CUDA)", value: "120 TFLOPS", note: "dense" },
    { dataType: "FP64", value: "Not published", note: "RTX-class FP64 is low — not an HPC-FP64 part" },
    { dataType: "RT Core (peak)", value: "355 TFLOPS", note: "graphics only" },
  ],
  swStack: [
    { layer: "Inference", component: "TensorRT-LLM (NVFP4), vLLM, SGLang, Triton, NIM", role: "FP4-native LLM serving at enterprise volume" },
    { layer: "Physical AI / OVX", component: "Omniverse, OpenUSD, Isaac", role: "Digital-twin and simulation workloads" },
    { layer: "Virtualisation", component: "vGPU; MIG", role: "4-way MIG isolation" },
    { layer: "NVIDIA AI Enterprise", component: "Not included with the GPU — licensed separately", role: "Contrast with H200 NVL's bundled 5-year subscription" },
  ],
  hostRecommendation: xeon6HostRows(96, 1536, 12),
  virtualization: [
    { label: "PCIe passthrough (whole GPU → VM)", value: "Supported" },
    { label: "MIG (hardware partitions)", value: "Supported — 1g.24gb smallest profile, up to 4 instances/GPU" },
    { label: "MIG-backed vGPU", value: "Supported — 8 GB min, up to 12/GPU (DC-1-8C: 3 per 1g slice × 4 slices)" },
    { label: "vGPU time-sliced inside a MIG slice", value: "Supported" },
    { label: "Time-sliced vGPU (compute, C-series)", value: "Supported — 8 GB min, up to 12/GPU" },
    { label: "Graphics vGPU (vPC/vWS)", value: "Supported" },
    { label: "Smallest isolated (memory-fenced) unit", value: "8 GB" },
    { label: "Max isolated slots / GPU", value: "12 (96 across an 8-GPU node)" },
    { label: "Memory wasted at the isolation floor for a 1 GB model", value: "87.5%" },
    { label: "NVIDIA AI Enterprise licensing", value: "Not bundled with this GPU (unlike H200 NVL) — licensed separately; NVIDIA has offered discounted NVAIE bundling via Lenovo" },
  ],
  caveats: [
    "TF32 (234 TFLOPS) vs. BF16 (1 PFLOP) is a 4.3:1 ratio, not the 2:1 ladder every other data type follows on this part — either TF32 is already dense or BF16 is quoted on a different convention. Affects all dense derivations from these two rows; confirm against the datasheet footnotes before using either in a bid.",
    "INT8 and FP64 are not published — classic INT8 pipelines and any HPC-FP64 use case have no first-party number to plan against.",
    "Real multi-GPU all-reduce bandwidth behind OEM PCIe switches is not vendor-published — measure with nccl-tests on the target chassis before committing to a tensor-parallel design.",
    "Street price has moved: one reseller source reports three consecutive ~30% baseline price hikes through 2026 — timestamp all pricing before quoting a business case.",
    "Same core silicon as the Workstation Edition (NVIDIA_RTX_PRO_6000 on this page) but a different published memory-bandwidth figure (1,597 vs. 1,792 GB/s) — don't average or interchange the two.",
    "MIG instance count (4) and MIG-backed vGPU count (12) differ because a single MIG partition can host multiple smaller vGPUs — don't conflate 'max MIG instances' with 'max isolated tenants.'",
    "Software-level sharing (Kubernetes GPU-Operator time-slicing, MPS ≤48 clients, HAMi/KAI fractional, many models per Triton/vLLM process) works here too, same as every other GPU on this page — none of it is hardware-isolated.",
  ],
  sources: [
    { id: "N2", label: "NVIDIA — RTX PRO 6000 Blackwell Server Edition product page (spec table)", url: "https://www.nvidia.com/en-us/data-center/rtx-pro-6000-blackwell-server-edition/" },
    { id: "N5", label: "NVIDIA — H200 product page (H200 NVL positioning, 5-yr NVAIE, used as the comparison baseline)", url: "https://www.nvidia.com/en-us/data-center/h200/" },
    { id: "N7", label: "NVIDIA Newsroom — RTX PRO Servers in mainstream enterprise systems (11 Aug 2025)", url: "https://nvidianews.nvidia.com/news/nvidia-rtx-pro-servers-with-blackwell-coming-to-worlds-most-popular-enterprise-systems" },
    { id: "M3", label: "MSI — RTX PRO Server lineup press release (26 Aug 2025)", url: "https://www.msi.com/news/detail/MSI-Expands-NVIDIA-RTX-PRO-Server-Lineup---Accelerated-by-RTX-PRO-6000-Blackwell-Server-Edition-GPU-146930" },
    { id: "S3", label: "Supermicro — SYS-522GA-NRT datasheet / eStore", url: "https://www.supermicro.com/en/products/system/datasheet/sys-522ga-nrt" },
    { id: "H5", label: "Express Computer Systems — DL380a Gen12 configurable part list", url: "https://expresscomputersystems.com/products/hpe-proliant-dl380a-rack-server-gen-12-configurable" },
    { id: "P6", label: "IBM Community — Lenovo RTX PRO 6000 / H200 NVL options (NVAIE inclusion)", url: "https://community.ibm.com/community/user/discussion/new-lenovo-nvidia-gpu-options-rtx-pro-6000-blackwell-server-edition-and-h200-nvl" },
    { id: "X1", label: "StorageReview — HPE AI Factory / Vera Rubin roadmap (21 Jul 2026)", url: "https://www.storagereview.com/news/hpe-cray-gx5000-and-ai-factory-get-nvidia-vera-rubin-nvl72-quantum-x800-infiniband-and-new-blackwell-options" },
    { id: "L1", label: "Lenovo Press LP2264 — ThinkSystem SR680a V4 Product Guide (Xeon 6 lane/host-sizing table)", url: "https://lenovopress.lenovo.com/lp2264-thinksystem-sr680a-v4-server" },
    { id: "N-VGPU-BW", label: "NVIDIA AI Enterprise 8.2 — Blackwell vGPU reference (MIG/vGPU types)", url: "https://docs.nvidia.com/ai-enterprise/release-8/latest/infra-software/vgpu/reference/blackwell.html" },
  ],
  sourceNote: "Compiled from NVIDIA's public RTX PRO 6000 Blackwell Server Edition product page, NVIDIA Newsroom, and OEM (Supermicro, HPE, Lenovo, MSI) product materials (Sep 2026). Virtualization/licensing figures from NVIDIA AI Enterprise 8.2's Blackwell vGPU reference (Sep 2026). Re-verify against nvidia.com and docs.nvidia.com before using in a bid or business case.",
};
