export type Category =
  | "OCR & Document"
  | "Vision & Multimodal"
  | "Speech & Audio"
  | "Translation"
  | "Embeddings & Retrieval"
  | "Safety & Guardrails"
  | "LLM";

export interface Model {
  name: string;
  hfId: string;
  category: Category;
  year: number;
  yearLabel: string;
  params: string;
  tasks: string[];
  modelSize: string;
  vram: string;
  quantization: string[];
  multilingual: string;
  cpuSupport: boolean;
  commercial: boolean;
  origin: string;
  maintained: boolean;
  serving: string[];
  benchmark: string;
  keyBenchmarks: string;
  recommendedUse: string;
  knownLimitations: string;
  hfAdoption: string;
  cloudEdge: string;
  finetuning: boolean;
  dockerSupport: boolean;
  architecture: string;
  maxTokens: string;
  /**
   * Decoder architecture specs for KV-cache/VRAM sizing (production-sizing tab only).
   * Left undefined unless sourced from a published config — never a guess. `paramsB` is
   * total resident params (MoE: all experts, not just active), used for weight VRAM.
   */
  paramsB?: number;
  numLayers?: number;
  numKvHeads?: number;
  headDim?: number;
}

/** The default model, latency SLA, silicon, and concurrency chosen for a task type (OCR,
 *  Classification, Reason, ...) — global, app-wide, not scoped to a Project. Manually curated
 *  today; the same row is the override slot for a future LLM-suggested default, editable at
 *  any time by a Presales architect. */
export interface TaskModelDefault {
  id: number;
  task_type: string;
  model_name: string;
  latency_sec: number | null;
  silicon: string | null;
  default_concurrency: number | null;
  requests_per_day: number | null;
  processing_window_hrs: number | null;
  updated_at: string;
}

export const CATEGORY_ORDER: Category[] = [
  "OCR & Document",
  "Vision & Multimodal",
  "Speech & Audio",
  "Translation",
  "Embeddings & Retrieval",
  "Safety & Guardrails",
  "LLM",
];

export const CATEGORY_COLORS: Record<
  Category,
  { row: string; rowAlt: string; badge: string; badgeText: string; accent: string }
> = {
  "OCR & Document":         { row: "bg-sky-50",       rowAlt: "bg-sky-100/60",      badge: "bg-sky-100",      badgeText: "text-sky-700",      accent: "#0ea5e9" },
  "Vision & Multimodal":    { row: "bg-violet-50",    rowAlt: "bg-violet-100/60",   badge: "bg-violet-100",   badgeText: "text-violet-700",   accent: "#7c3aed" },
  "Speech & Audio":         { row: "bg-emerald-50",   rowAlt: "bg-emerald-100/60",  badge: "bg-emerald-100",  badgeText: "text-emerald-700",  accent: "#059669" },
  "Translation":            { row: "bg-amber-50",     rowAlt: "bg-amber-100/60",    badge: "bg-amber-100",    badgeText: "text-amber-700",    accent: "#d97706" },
  "Embeddings & Retrieval": { row: "bg-blue-50",      rowAlt: "bg-blue-100/60",     badge: "bg-blue-100",     badgeText: "text-blue-700",     accent: "#2563eb" },
  "Safety & Guardrails":    { row: "bg-rose-50",      rowAlt: "bg-rose-100/60",     badge: "bg-rose-100",     badgeText: "text-rose-700",     accent: "#e11d48" },
  "LLM":                    { row: "bg-indigo-50",    rowAlt: "bg-indigo-100/60",   badge: "bg-indigo-100",   badgeText: "text-indigo-700",   accent: "#4f46e5" },
};

export const models: Model[] = [
  // OCR & Document
  {
    name: "dots.mocr", hfId: "rednote-hilab/dots.mocr", category: "OCR & Document",
    year: 2026, yearLabel: "2026", params: "3B",
    tasks: [],
    modelSize: "~6–7 GB", vram: "", quantization: [],
    multilingual: "100+ languages, strong CJK + Indic (Kannada shown)", cpuSupport: false, commercial: false,
    origin: "China (RedNote / Xiaohongshu AI Lab)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Best open-source doc parsing; multilingual PDF; charts→SVG; academic papers",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Multimodal OCR VLM (Qwen3-VL-4B base) + unified text+graphics parser", maxTokens: "",
  },
  {
    name: "GLM-OCR", hfId: "zai-org/GLM-OCR", category: "OCR & Document",
    year: 2026, yearLabel: "2026", params: "0.9B",
    tasks: [],
    modelSize: "~1.8 GB", vram: "", quantization: [],
    multilingual: "8 languages, strong CJK", cpuSupport: false, commercial: false,
    origin: "China (Zhipu AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "High-accuracy production OCR, complex table/formula/seal recognition",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "GLM-V encoder-decoder + CogViT visual encoder", maxTokens: "",
  },
  {
    name: "LightOnOCR-2-1B", hfId: "lightonai/LightOnOCR-2-1B", category: "OCR & Document",
    year: 2026, yearLabel: "2026", params: "1B",
    tasks: [],
    modelSize: "~2 GB", vram: "", quantization: [],
    multilingual: "English, French, German, Spanish, Italian, Dutch, Portuguese, Swedish, Danish, Chines, Japanese", cpuSupport: false, commercial: false,
    origin: "EU — France (LightOn AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "High-throughput OCR, document digitization, tables/forms/receipts, scientific papers, math & LaTeX extraction",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Mistral-based end-to-end vision-language OCR model", maxTokens: "",
  },
  // Vision & Multimodal
  {
    name: "InternVL3-8B", hfId: "OpenGVLab/InternVL3-8B", category: "Vision & Multimodal",
    year: 2025, yearLabel: "2025", params: "8B",
    tasks: [],
    modelSize: "~16 GB", vram: "", quantization: [],
    multilingual: "English, Chinese, Portuguese, Arabic, Turkish, Russian", cpuSupport: false, commercial: false,
    origin: "China (OpenGVLab / Shanghai AI Lab)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "High-accuracy document intelligence, OCR, charts, STEM reasoning, GUI agents, video understanding",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "InternViT vision encoder + MLP projector + Qwen2.5-7B language model", maxTokens: "",
  },
  {
    name: "Llama-3.2-11B-Vision-Instruct", hfId: "meta-llama/Llama-3.2-11B-Vision-Instruct", category: "Vision & Multimodal",
    year: 2024, yearLabel: "2024", params: "11B (10.7B)",
    tasks: [],
    modelSize: "~22 GB BF16 · ~6 GB INT4", vram: "", quantization: [],
    multilingual: "English, Germna, French, Italian, Portuguese, Hindi, Spanish, Thai", cpuSupport: false, commercial: false,
    origin: "USA (Meta)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "General image understanding, visual QA, document QA, charts/graphs, multimodal assistants",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "ViT vision encoder + cross-attention adapter + Llama text backbone", maxTokens: "",
  },
  {
    name: "Qwen3-VL-4B-Instruct", hfId: "Qwen/Qwen3-VL-4B-Instruct", category: "Vision & Multimodal",
    year: 2025, yearLabel: "2025", params: "4B",
    tasks: [],
    modelSize: "~8 GB", vram: "", quantization: [],
    multilingual: "Romanian, Swahili, Russian, Hindi, Hebrew, Polish, Cebuano, Italian, German, Vietnamese, Ukranian, Uzbek, Spanish, French, Portuguese, Japnese, Turkish, Kazakh, Korean, Arabic, Persian, Urdu, Finnish, Dutch, Norwegian, Czech, Greek, Thai, Indonesian, Danish, Serbian, Swedish ", cpuSupport: false, commercial: false,
    origin: "China (Alibaba / Qwen Team)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Document OCR/extraction, forms/invoices, charts & tables, GUI agents, video understanding, multimodal reasoning",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Vision Transformer + multimodal projector + Qwen language backbone", maxTokens: "",
  },
  // Speech & Audio
  {
    name: "Cohere Transcribe 03-2026", hfId: "CohereLabs/cohere-transcribe-03-2026", category: "Speech & Audio",
    year: 2026, yearLabel: "2026", params: "2B",
    tasks: [],
    modelSize: "~4 GB", vram: "", quantization: [],
    multilingual: "Arabic, German, Greek, English, Spanish, French, Italian, Japnese, Korean, Dutch, Polish, Portuguese, Vietnamese, Chinese", cpuSupport: false, commercial: false,
    origin: "Canada (Cohere)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Multilingual transcription, enterprise call transcription, meetings, voice pipelines, diarization-aware ASR",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Multilingual transcription, enterprise call transcription, meetings, voice pipelines, diarization-aware ASR", maxTokens: "",
  },
  {
    name: "Distil-Whisper large-v3", hfId: "distil-whisper/distil-large-v3", category: "Speech & Audio",
    year: 2024, yearLabel: "2024", params: "756M",
    tasks: [],
    modelSize: "~1.5 GB (FP16)", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "USA (Hugging Face)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Fast English transcription, long-form audio, podcasts/meetings, streaming and latency-sensitive ASR",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Distilled Whisper encoder-decoder Transformer", maxTokens: "",
  },
  {
    name: "IndicConformer-600M-Multilingual", hfId: "ai4bharat/indic-conformer-600m-multilingual", category: "Speech & Audio",
    year: 2025, yearLabel: "2025", params: "600M",
    tasks: [],
    modelSize: "~2.4 GB", vram: "", quantization: [],
    multilingual: "Assamese, Bengali, Bodo, Dogri, Gujarati, Hindi, Kannada, Konkani, Kashmiri, Maithili, Malayalam, Manipuri, Marathi, Nepali, Odia, Punjabi, Sanskrit, Santali, Sindhi, Tamil, Telugu, Urdu", cpuSupport: false, commercial: false,
    origin: "India (AI4Bharat / IIT Madras)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Indian-language ASR, call centers, voice assistants, transcription and Bhashini-style applications",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Conformer encoder + CTC/RNN-T decoding", maxTokens: "",
  },
  {
    name: "Orpheus-3B-0.1-ft", hfId: "canopylabs/orpheus-3b-0.1-ft", category: "Speech & Audio",
    year: 2025, yearLabel: "2025", params: "3B",
    tasks: [],
    modelSize: "~6 GB BF16 · ~2 GB INT4", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "USA (Canopy Labs)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Low-latency TTS, expressive voice agents, conversational speech, zero-shot voice cloning",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Autoregressive LLM generating neural audio-codec tokens", maxTokens: "",
  },
  {
    name: "pyannote speaker-diarization", hfId: "pyannote/speaker-diarization-community-1", category: "Speech & Audio",
    year: 2025, yearLabel: "2025", params: "~37M total pipeline",
    tasks: [],
    modelSize: "~150 MB total", vram: "", quantization: [],
    multilingual: "NA", cpuSupport: false, commercial: false,
    origin: "France (pyannote.audio)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Meeting/call diarization, speaker segmentation, multi-speaker transcription pipelines",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Speech segmentation + speaker embeddings + clustering pipeline", maxTokens: "",
  },
  {
    name: "Silero VAD v5", hfId: "snakers4/silero-vad", category: "Speech & Audio",
    year: 2025, yearLabel: "2025", params: "~1–2M (LSTM-based)",
    tasks: [],
    modelSize: "~2 MB (v5)", vram: "", quantization: [],
    multilingual: "NA", cpuSupport: false, commercial: false,
    origin: "Russia (Silero team)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Fast CPU VAD, speech timestamps, streaming ASR preprocessing, voice-agent turn detection",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Lightweight recurrent neural network VAD", maxTokens: "",
  },
  {
    name: "TEN VAD", hfId: "TEN-framework/ten-vad", category: "Speech & Audio",
    year: 2025, yearLabel: "2025", params: "Very small (C-native + ONNX)",
    tasks: [],
    modelSize: "<1 MB", vram: "", quantization: [],
    multilingual: "NA", cpuSupport: false, commercial: false,
    origin: "TEN Framework", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Real-time voice agents, conversational turn detection, edge/IoT streaming VAD",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Lightweight streaming neural VAD with ONNX/C runtime", maxTokens: "",
  },
  // Translation
  {
    name: "IndicTrans2 En→Indic 1B", hfId: "ai4bharat/indictrans2-en-indic-1B", category: "Translation",
    year: 2024, yearLabel: "2024", params: "1.1B",
    tasks: [],
    modelSize: "~4 GB", vram: "", quantization: [],
    multilingual: "Assamese, Bengali, Bodo, Dogri, Gujarati, English, Hindi, Kannada, Kashmiri, Konkani, Maithili, Malayalam, Manipuri, Marathi, Nepali, Odia, Punjabi, Sanskrit, Santali, Sindhi, Tamil, Telugu, Urdu, English", cpuSupport: false, commercial: false,
    origin: "India (AI4Bharat / IIT Madras)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "English localization into Indian languages, government/public-service translation, multilingual content pipelines",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Encoder-decoder Transformer", maxTokens: "",
  },
  {
    name: "IndicTrans2 Indic→En 1B", hfId: "ai4bharat/indictrans2-indic-en-1B", category: "Translation",
    year: 2024, yearLabel: "2024", params: "1.1B",
    tasks: [],
    modelSize: "~4 GB", vram: "", quantization: [],
    multilingual: "Assamese, Bengali, Bodo, Dogri, Gujarati, English, Hindi, Kannada, Kashmiri, Konkani, Maithili, Malayalam, Manipuri, Marathi, Nepali, Odia, Punjabi, Sanskrit, Santali, Sindhi, Tamil, Telugu, Urdu, English", cpuSupport: false, commercial: false,
    origin: "India (AI4Bharat / IIT Madras)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Indian-language content → English, search/indexing, support and document translation",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Encoder-decoder Transformer", maxTokens: "",
  },
  {
    name: "IndicTrans2 Indic→Indic 1B", hfId: "ai4bharat/indictrans2-indic-indic-1B", category: "Translation",
    year: 2024, yearLabel: "2024", params: "1B",
    tasks: [],
    modelSize: "~4 GB", vram: "", quantization: [],
    multilingual: "Assamese, Bengali, Bodo, Dogri, Gujarati, English, Hindi, Kannada, Kashmiri, Konkani, Maithili, Malayalam, Manipuri, Marathi, Nepali, Odia, Punjabi, Sanskrit, Santali, Sindhi, Tamil, Telugu, Urdu ", cpuSupport: false, commercial: false,
    origin: "India (AI4Bharat / IIT Madras)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Direct translation between Indian languages without English pivoting",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Encoder-decoder Transformer", maxTokens: "",
  },
  {
    name: "Sarvam Translate", hfId: "sarvamai/sarvam-translate", category: "Translation",
    year: 2025, yearLabel: "2025", params: "4B",
    tasks: [],
    modelSize: "~8B", vram: "", quantization: [],
    multilingual: "Assamese, Bengali, Bodo, Dogri, Gujarati, English, Hindi, Kannada, Kashmiri, Konkani, Maithili, Malayalam, Manipuri, Marathi, Nepali, Odia, Punjabi, Sanskrit, Santali, Sindhi, Tamil, Telugu, Urdu, English", cpuSupport: false, commercial: false,
    origin: "India (AI4Bharat + Sarvam)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "High-quality Indian-language translation, localization, multilingual enterprise applications",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Gemma-based instruction-tuned translation model", maxTokens: "",
  },
  // Embeddings & Retrieval
  {
    name: "BGE-large-en-v1.5", hfId: "BAAI/bge-large-en-v1.5", category: "Embeddings & Retrieval",
    year: 2023, yearLabel: "2023", params: "335M",
    tasks: [],
    modelSize: "~1.3 GB", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "China (BAAI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "English semantic search, RAG retrieval, document similarity, knowledge-base search",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "BERT-style bi-encoder embedding model", maxTokens: "",
  },
  {
    name: "BGE-M3", hfId: "BAAI/bge-m3", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024", params: "568M",
    tasks: [],
    modelSize: "~2.3 GB", vram: "", quantization: [],
    multilingual: "100+ languages", cpuSupport: false, commercial: false,
    origin: "China (BAAI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Multilingual RAG, hybrid search, long-document retrieval, dense + lexical + multi-vector retrieval",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "XLM-R based multilingual embedding model supporting dense, sparse and multi-vector retrieval", maxTokens: "",
  },
  {
    name: "BGE-reranker-v2-m3", hfId: "BAAI/bge-reranker-v2-m3", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024", params: "568M",
    tasks: [],
    modelSize: "~2.3 GB", vram: "", quantization: [],
    multilingual: "100+ languages", cpuSupport: false, commercial: false,
    origin: "China (BAAI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Second-stage RAG reranking, multilingual search, improving top-k retrieval precision",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "XLM-R based cross-encoder reranker", maxTokens: "",
  },
  {
    name: "ColPali / ColVision Family", hfId: "vidore/colpali-v1.3", category: "Embeddings & Retrieval",
    year: 2025, yearLabel: "2025", params: "ColPali-v1.3: ~3B · ColQwen2.5: ~3B",
    tasks: [],
    modelSize: "~6 GB", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "France (CentraleSupélec / HuggingFace)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Visually rich PDF RAG, slides, scanned documents, charts/tables, retrieval without OCR-first pipelines",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Vision-language encoder + ColBERT-style multi-vector late interaction", maxTokens: "",
  },
  {
    name: "jina-reranker-v2-base-multilingual", hfId: "jinaai/jina-reranker-v2-base-multilingual", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024", params: "278M",
    tasks: [],
    modelSize: "~1.1 GB", vram: "", quantization: [],
    multilingual: "100+ languages", cpuSupport: false, commercial: false,
    origin: "Germany (Jina AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Lightweight multilingual RAG reranking, semantic search, agent retrieval",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "XLM-R based cross-encoder reranker", maxTokens: "",
  },
  {
    name: "Semantic Router", hfId: "aurelio-labs/semantic-router", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024", params: "Encoder-dependent (default: 22M MiniLM)",
    tasks: [],
    modelSize: "Encoder-dependent", vram: "", quantization: [],
    multilingual: "NA", cpuSupport: false, commercial: false,
    origin: "UK (Aurelio AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Intent routing, model routing, tool selection, agent routing without training a classifier",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Embedding encoder + similarity-based routing", maxTokens: "",
  },
  // Safety & Guardrails
  {
    name: "Granite-Guardian-3.0-2B", hfId: "ibm-granite/granite-guardian-3.0-2b", category: "Safety & Guardrails",
    year: 2024, yearLabel: "2024", params: "2B",
    tasks: [],
    modelSize: "~4 GB", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "USA (IBM Research)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Enterprise prompt/response moderation, jailbreak detection, harmful-content and risk classification",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Granite decoder-only Transformer fine-tuned for safety classification", maxTokens: "",
  },
  {
    name: "Llama-Guard-3-8B", hfId: "meta-llama/Llama-Guard-3-8B", category: "Safety & Guardrails",
    year: 2024, yearLabel: "2024", params: "8B",
    tasks: [],
    modelSize: "~16 GB", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "USA (Meta AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Input/output moderation, policy enforcement, hazard classification",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Llama decoder-only Transformer fine-tuned as a safety classifier", maxTokens: "",
  },
  {
    name: "openai/privacy-filter", hfId: "openai/privacy-filter", category: "Safety & Guardrails",
    year: 2026, yearLabel: "2026", params: "1.5B (50M active)",
    tasks: [],
    modelSize: "~3 GB", vram: "", quantization: [],
    multilingual: "English", cpuSupport: false, commercial: false,
    origin: "USA (OpenAI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "PII detection/redaction, privacy filtering, compliance preprocessing",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Token-classification / NER model", maxTokens: "",
  },
  {
    name: "Qwen3Guard-Gen-4B", hfId: "Qwen/Qwen3Guard-Gen-4B", category: "Safety & Guardrails",
    year: 2025, yearLabel: "2025", params: "4B",
    tasks: [],
    modelSize: "~8 GB BF16 · ~2 GB INT4", vram: "", quantization: [],
    multilingual: "119 languages", cpuSupport: false, commercial: false,
    origin: "China (Alibaba / Qwen Team)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Multilingual prompt/response moderation, guardrails, risk classification",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Qwen decoder-only Transformer fine-tuned for safety classification", maxTokens: "",
  },
  {
    name: "ShieldGemma-2B", hfId: "google/shieldgemma-2b", category: "Safety & Guardrails",
    year: 2024, yearLabel: "2024", params: "2B",
    tasks: [],
    modelSize: "~4 GB", vram: "", quantization: [],
    multilingual: "Multilingual (Gemma backbone)", cpuSupport: false, commercial: false,
    origin: "USA (Google DeepMind)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Production content moderation; pre/post-inference safety filtering",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Gemma 2B; instruction-tuned for content policy classification", maxTokens: "",
  },
  // LLM
  {
    name: "Gemma 4 26B-A4B-IT", hfId: "google/gemma-4-26B-A4B-it", category: "LLM",
    year: 2026, yearLabel: "2026", params: "25.2B total · 3.8B active (MoE)",
    tasks: [],
    modelSize: "~50 GB BF16 · ~13 GB INT4", vram: "", quantization: [],
    multilingual: "140+ languages", cpuSupport: false, commercial: false,
    origin: "USA (Google DeepMind)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Multimodal reasoning, general assistants, document analysis, coding/math, lower-active-parameter serving",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Mixture-of-Experts multimodal Transformer", maxTokens: "",
  },
  {
    name: "Gemma-3-4B-it", hfId: "google/gemma-3-4b-it", category: "LLM",
    year: 2025, yearLabel: "2025", params: "4B",
    tasks: [],
    modelSize: "~8 GB BF16 · ~2.5 GB INT4", vram: "", quantization: [],
    multilingual: "140+ languages", cpuSupport: false, commercial: false,
    origin: "USA (Google DeepMind)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Small multimodal assistants, summarization, document QA, long-context workloads",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Dense multimodal Transformer", maxTokens: "",
  },
  {
    name: "Gemma-4-E4B-it", hfId: "google/gemma-4-e4b-it", category: "LLM",
    year: 2026, yearLabel: "2026", params: "4B (effective)",
    tasks: [],
    modelSize: "~8 GB BF16 · ~2.5 GB INT4", vram: "", quantization: [],
    multilingual: "140+ languages", cpuSupport: false, commercial: false,
    origin: "USA (Google DeepMind)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Lightweight local assistant, summarization, general text generation",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Dense decoder-only Transformer", maxTokens: "",
  },
  {
    name: "GPT-OSS-120B", hfId: "openai/gpt-oss-120b", category: "LLM",
    year: 2025, yearLabel: "2025", params: "117B total · 5.1B active (MoE)",
    tasks: [],
    modelSize: "~234 GB BF16 · ~60 GB MXFP4 (native)", vram: "", quantization: [],
    multilingual: "Arabic, Bengali, Chinese, French, German, Hindi, Indonesian, Italian, Japanese, Korean, Portuguese, Spanish, Swahili, Yoruba", cpuSupport: false, commercial: false,
    origin: "USA (OpenAI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Complex reasoning, coding, code review, agentic workflows, tool use, long-form generation",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Mixture-of-Experts decoder-only Transformer", maxTokens: "",
  },
  {
    name: "LFM2.5-1.2B-Instruct", hfId: "LiquidAI/LFM2.5-1.2B-Instruct", category: "LLM",
    year: 2025, yearLabel: "2025", params: "1.2B",
    tasks: [],
    modelSize: "~2.4 GB", vram: "", quantization: [],
    multilingual: "English, Arabic, Chinese, French, German, Japanese, Korean, Spanish", cpuSupport: false, commercial: false,
    origin: "USA (Liquid AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "On-device/CPU assistant, lightweight chat, classification, simple task execution",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Hybrid Liquid Foundation Model", maxTokens: "",
  },
  {
    name: "Llama 3.3 70B Instruct", hfId: "meta-llama/Llama-3.3-70B-Instruct", category: "LLM",
    year: 2024, yearLabel: "2024", params: "70.6B",
    tasks: [],
    modelSize: "~141 GB BF16 · ~35 GB INT4", vram: "", quantization: [],
    multilingual: "English, French, Italian, Portuguese, Hindi, Spanish, Thai, German", cpuSupport: false, commercial: false,
    origin: "USA (Meta)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "General reasoning, long-form generation, enterprise assistants, tool use",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Dense decoder-only Transformer with GQA", maxTokens: "",
  },
  {
    name: "Llama-3.2-1B-it", hfId: "meta-llama/Llama-3.2-1B-Instruct", category: "LLM",
    year: 2024, yearLabel: "2024", params: "1.24B",
    tasks: [],
    modelSize: "~2.5 GB BF16 · ~0.7 GB INT4", vram: "", quantization: [],
    multilingual: "English, French, Italian, Portuguese, Hindi, Spanish, Thai, German", cpuSupport: false, commercial: false,
    origin: "USA (Meta)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "General reasoning, long-form generation, enterprise assistants, tool use",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Dense decoder-only Transformer with GQA", maxTokens: "",
  },
  {
    name: "Llama-3.2-8B-it", hfId: "meta-llama/Llama-3.2-8B-Instruct", category: "LLM",
    year: 2024, yearLabel: "2024", params: "8B",
    tasks: [],
    modelSize: "~16 GB BF16 · ~4 GB INT4", vram: "", quantization: [],
    multilingual: "English, French, Italian, Portuguese, Hindi, Spanish, Thai, German", cpuSupport: false, commercial: false,
    origin: "USA (Meta)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "General chat, summarization, extraction, RAG generation, moderate-cost local serving",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "General chat, summarization, extraction, RAG generation, moderate-cost local serving", maxTokens: "",
  },
  {
    name: "Qwen3-30B-A3B", hfId: "Qwen/Qwen3-30B-A3B", category: "LLM",
    year: 2025, yearLabel: "2025", params: "30.5B total · 3.3B active (MoE)",
    tasks: [],
    modelSize: "~60 GB BF16 · ~15 GB INT4", vram: "", quantization: [],
    multilingual: "119+ Languages", cpuSupport: false, commercial: false,
    origin: "China (Alibaba / Qwen Team)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Coding, math, reasoning, tool use, local agents and cost-efficient high-throughput inference",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Mixture-of-Experts decoder-only Transformer", maxTokens: "",
  },
  {
    name: "Qwen3.5-4B", hfId: "Qwen/Qwen3.5-4B", category: "LLM",
    year: 2026, yearLabel: "2026", params: "4B",
    tasks: [],
    modelSize: "~8 GB BF16 · ~2 GB INT4", vram: "", quantization: [],
    multilingual: "119+ Languages", cpuSupport: false, commercial: false,
    origin: "China (Alibaba / Qwen Team)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Low-latency chat, edge/on-device inference, cost-efficient high-concurrency serving",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Dense decoder-only Transformer with GQA", maxTokens: "",
  },
  {
    name: "Qwen3.6-27B", hfId: "Qwen/Qwen3.6-27B", category: "LLM",
    year: 2026, yearLabel: "2026", params: "27B",
    tasks: [],
    modelSize: "~54 GB BF16 · ~14 GB INT4", vram: "", quantization: [],
    multilingual: "119+ Languages", cpuSupport: false, commercial: false,
    origin: "China (Alibaba / Qwen Team)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Coding agents, long-context reasoning, tool use, general-purpose local inference",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Dense decoder-only Transformer with GQA", maxTokens: "",
  },
  {
    name: "Sarvam-30B", hfId: "sarvamai/sarvam-30b", category: "LLM",
    year: 2026, yearLabel: "2026", params: "30B total · ~2.4B active (MoE)",
    tasks: [],
    modelSize: "~60 GB BF16 · ~15 GB FP8", vram: "", quantization: [],
    multilingual: "23 languages", cpuSupport: false, commercial: false,
    origin: "India (Sarvam AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Indic-language assistants, voice agents, multilingual reasoning, code and tool use",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Mixture-of-Experts decoder-only Transformer", maxTokens: "",
  },
  {
    name: "Sarvam-105B", hfId: "sarvamai/sarvam-105b", category: "LLM",
    year: 2026, yearLabel: "2026", params: "105",
    tasks: [],
    modelSize: "105 FP8", vram: "", quantization: [],
    multilingual: "23 Languages", cpuSupport: false, commercial: false,
    origin: "India (Sarvam AI)", maintained: false,
    serving: [],
    benchmark: "",
    keyBenchmarks: "",
    recommendedUse: "Indic-language assistants, voice agents, multilingual reasoning, code and tool use",
    knownLimitations: "",
    hfAdoption: "",
    cloudEdge: "", finetuning: false, dockerSupport: false,
    architecture: "Mixture-of-Experts decoder-only Transformer", maxTokens: "",
  },
];
