export type Category =
  | "OCR & Document"
  | "Vision & Multimodal"
  | "Speech & Audio"
  | "Translation"
  | "Embeddings & Retrieval"
  | "Safety & Guardrails"
  | "LLM"
  | "Code & Agents";

export interface Model {
  name: string;
  hfId: string;
  category: Category;
  year: number;
  yearLabel: string;
  params: string;
  tasks: string[];
  modelSize: string;
  vram: string;
  quantization: string[];
  multilingual: string;
  cpuSupport: boolean;
  commercial: boolean;
  origin: string;
  maintained: boolean;
  serving: string[];
  benchmark: string;
  keyBenchmarks: string;
  recommendedUse: string;
  knownLimitations: string;
  hfAdoption: string;
  cloudEdge: string;
  finetuning: boolean;
  dockerSupport: boolean;
  architecture: string;
  maxTokens: string;
  /**
   * Decoder architecture specs for KV-cache/VRAM sizing (production-sizing tab only).
   * Left undefined unless sourced from a published config — never a guess. `paramsB` is
   * total resident params (MoE: all experts, not just active), used for weight VRAM.
   */
  paramsB?: number;
  numLayers?: number;
  numKvHeads?: number;
  headDim?: number;
}

export const CATEGORY_ORDER: Category[] = [
  "OCR & Document",
  "Vision & Multimodal",
  "Speech & Audio",
  "Translation",
  "Embeddings & Retrieval",
  "Safety & Guardrails",
  "LLM",
  "Code & Agents",
];

export const CATEGORY_COLORS: Record<
  Category,
  { row: string; rowAlt: string; badge: string; badgeText: string; accent: string }
> = {
  "OCR & Document":         { row: "bg-sky-50",       rowAlt: "bg-sky-100/60",      badge: "bg-sky-100",      badgeText: "text-sky-700",      accent: "#0ea5e9" },
  "Vision & Multimodal":    { row: "bg-violet-50",    rowAlt: "bg-violet-100/60",   badge: "bg-violet-100",   badgeText: "text-violet-700",   accent: "#7c3aed" },
  "Speech & Audio":         { row: "bg-emerald-50",   rowAlt: "bg-emerald-100/60",  badge: "bg-emerald-100",  badgeText: "text-emerald-700",  accent: "#059669" },
  "Translation":            { row: "bg-amber-50",     rowAlt: "bg-amber-100/60",    badge: "bg-amber-100",    badgeText: "text-amber-700",    accent: "#d97706" },
  "Embeddings & Retrieval": { row: "bg-blue-50",      rowAlt: "bg-blue-100/60",     badge: "bg-blue-100",     badgeText: "text-blue-700",     accent: "#2563eb" },
  "Safety & Guardrails":    { row: "bg-rose-50",      rowAlt: "bg-rose-100/60",     badge: "bg-rose-100",     badgeText: "text-rose-700",     accent: "#e11d48" },
  "LLM":                    { row: "bg-indigo-50",    rowAlt: "bg-indigo-100/60",   badge: "bg-indigo-100",   badgeText: "text-indigo-700",   accent: "#4f46e5" },
  "Code & Agents":          { row: "bg-orange-50",    rowAlt: "bg-orange-100/60",   badge: "bg-orange-100",   badgeText: "text-orange-700",   accent: "#ea580c" },
};

export const models: Model[] = [
  // OCR & Document
  {
    name: "GLM-OCR", hfId: "zai-org/GLM-OCR", category: "OCR & Document",
    year: 2026, yearLabel: "2026 (Feb)", params: "0.9B",
    tasks: ["Text Recognition", "Formula Recognition", "Table Recognition", "Information Extraction"],
    modelSize: "~1.8 GB", vram: "~4–6 GB", quantization: ["BF16", "INT4/INT8 (vLLM)", "GGUF (Ollama)"],
    multilingual: "8 languages, strong CJK", cpuSupport: true, commercial: true,
    origin: "China (Zhipu AI)", maintained: true,
    serving: ["vLLM", "SGLang", "Ollama", "HF Transformers"],
    benchmark: "#1 on OmniDocBench V1.5 (94.62 overall)",
    keyBenchmarks: "OmniDocBench V1.5: 94.62 (#1), SOTA formula/table/extraction",
    recommendedUse: "High-accuracy production OCR, complex table/formula/seal recognition",
    knownLimitations: "Prompt modes limited to 2 types; JSON schema required for extraction",
    hfAdoption: "HF likes: 10 · GitHub: 5,400 stars",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "GLM-V encoder-decoder + CogViT visual encoder", maxTokens: "8192",
  },
  {
    name: "LightOnOCR-2-1B", hfId: "lightonai/LightOnOCR-2-1B", category: "OCR & Document",
    year: 2026, yearLabel: "2026 (Jan)", params: "1B",
    tasks: ["Document OCR", "Table Extraction", "Receipt & Form Parsing", "Math/LaTeX"],
    modelSize: "~2 GB", vram: "~8 GB", quantization: ["BF16", "INT4/INT8 (vLLM)", "float32"],
    multilingual: "11 languages, strong French & English", cpuSupport: true, commercial: true,
    origin: "EU — France (LightOn AI)", maintained: true,
    serving: ["vLLM", "HF Transformers"],
    benchmark: "#1 on OlmOCR-Bench (83.2 ± 0.9), 5.71 pages/s on H100",
    keyBenchmarks: "OlmOCR-Bench: 83.2 ± 0.9 (#1), 3.3× faster than Chandra OCR",
    recommendedUse: "High-throughput document pipelines, EU data compliance, scientific/arXiv",
    knownLimitations: "Requires transformers from source; PDFs must be pre-rendered to images",
    hfAdoption: "HF likes: 36 · 225 downloads/month",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "End-to-end VLM (Mistral3), fully differentiable, RLVR post-training", maxTokens: "4096",
  },
  {
    name: "PaddleOCR 3.0 / PP-OCRv5", hfId: "PaddlePaddle/PaddleOCR", category: "OCR & Document",
    year: 2025, yearLabel: "2025 (May)", params: "Mobile ~9 MB · Server ~120M",
    tasks: ["Text Detection & Recognition", "Handwriting OCR", "Table Structure Recognition", "Document Layout Analysis", "Key Info Extraction"],
    modelSize: "Mobile ~9 MB · Server ~200 MB", vram: "CPU: ~1–2 GB RAM · GPU: 4–8 GB",
    quantization: ["FP32", "FP16", "INT8", "Mobile quantized (~9 MB)"],
    multilingual: "100+ languages incl. CJK, Latin, Cyrillic, Arabic, Devanagari", cpuSupport: true, commercial: true,
    origin: "China (Baidu / PaddlePaddle)", maintained: true,
    serving: ["Python API", "CLI", "REST (Docker)", "ONNX Runtime", "TensorRT", "Mobile/edge"],
    benchmark: "#1 OmniDocBench OCR text · Outperforms Gemini 2.5 Pro & GPT-4o on OCR",
    keyBenchmarks: "PP-OCRv5: +13% over PP-OCRv4; #1 OmniDocBench OCR text",
    recommendedUse: "Best CPU/edge OCR; 100+ language pipelines; handwriting recognition",
    knownLimitations: "Two-stage pipeline complexity; PaddlePaddle framework dependency",
    hfAdoption: "GitHub: 50,000+ stars · millions of PyPI downloads",
    cloudEdge: "Both (9 MB mobile → server GPU)", finetuning: true, dockerSupport: true,
    architecture: "Two-stage: PP-OCRv5 (detect+recognize) + PP-StructureV3 layout", maxTokens: "N/A",
  },
  {
    name: "dots.mocr", hfId: "rednote-hilab/dots.mocr", category: "OCR & Document",
    year: 2026, yearLabel: "2026 (Mar)", params: "3B",
    tasks: ["Multilingual Document Parsing", "Table Extraction (HTML/Markdown)", "Formula Recognition (LaTeX)", "SVG Code Generation from Charts", "Web Page Parsing"],
    modelSize: "~6–7 GB", vram: "~10–14 GB", quantization: ["BF16", "fp8/awq/gptq (vLLM)"],
    multilingual: "100+ languages, strong CJK + Indic (Kannada shown)", cpuSupport: false, commercial: false,
    origin: "China (RedNote / Xiaohongshu AI Lab)", maintained: true,
    serving: ["vLLM (recommended)", "HF Transformers"],
    benchmark: "#1 open-source olmOCR-Bench (83.9) · SOTA OmniDocBench TextEdit",
    keyBenchmarks: "olmOCR-Bench: 83.9 (SOTA) · OmniDocBench TextEdit: 0.031 (SOTA)",
    recommendedUse: "Best open-source doc parsing; multilingual PDF; charts→SVG; academic papers",
    knownLimitations: "GPU required; custom license (not standard MIT); no GGUF/INT4 yet",
    hfAdoption: "dots.ocr predecessor: 260K downloads · 1.28K HF likes",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "Multimodal OCR VLM (Qwen3-VL-4B base) + unified text+graphics parser", maxTokens: "24000",
  },
  // Vision & Multimodal
  {
    name: "Qwen3-VL-4B-Instruct", hfId: "Qwen/Qwen3-VL-4B-Instruct", category: "Vision & Multimodal",
    year: 2025, yearLabel: "2025", params: "4B",
    tasks: ["Image Captioning", "Visual QA", "Document Understanding", "Chart & Table Analysis", "GUI Agent", "Video Understanding", "Math/STEM Reasoning"],
    modelSize: "~8 GB", vram: "~8 GB BF16 · ~4 GB INT4",
    quantization: ["BF16", "INT4/INT8 (vLLM)", "GGUF (53 community)", "AWQ", "GPTQ"],
    multilingual: "32 OCR languages, strong CJK + Arabic + Latin", cpuSupport: false, commercial: true,
    origin: "China (Alibaba / Qwen Team)", maintained: true,
    serving: ["HF Transformers", "vLLM", "SGLang", "LMDeploy", "Ollama"],
    benchmark: "#1 4B-class on DocVQA, ChartQA, MathVista, OCRBench",
    keyBenchmarks: "DocVQA, ChartQA, MathVista, OCRBench: #1 4B-class; beats Qwen2.5-VL-7B",
    recommendedUse: "Best general-purpose 4B VLM; production GPU; document/chart/GUI/video",
    knownLimitations: "GPU strongly preferred; Flash Attention 2 for optimal performance",
    hfAdoption: "HF likes: 331 · 965K downloads/month · 53 quantizations · 183 finetunes",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Interleaved-MRoPE + DeepStack ViT; 256K context (expandable to 1M)", maxTokens: "32768",
  },
  {
    name: "InternVL3-8B", hfId: "OpenGVLab/InternVL3-8B", category: "Vision & Multimodal",
    year: 2025, yearLabel: "2025 (Apr)", params: "8B",
    tasks: ["Image Captioning", "Visual QA", "Document Understanding", "OCR", "Math/STEM", "GUI Grounding", "Video Understanding", "3D Spatial Reasoning"],
    modelSize: "~16 GB", vram: "~16 GB BF16 · ~10 GB INT8",
    quantization: ["BF16", "BNB 8-bit", "AWQ/GPTQ (community)"],
    multilingual: "Multilingual — CJK, European, Arabic via Qwen2.5-7B backbone", cpuSupport: false, commercial: true,
    origin: "China (OpenGVLab / Shanghai AI Lab)", maintained: true,
    serving: ["HF Transformers", "LMDeploy (TurboMind)", "vLLM", "SWIFT"],
    benchmark: "SOTA open-source 8B VLM on OCR, chart, doc, math, GUI, video",
    keyBenchmarks: "Top 8B-class: OCR, DocVQA, ChartQA, Math, GUI grounding, video — #1 or near",
    recommendedUse: "Best open-source 8B VLM for accuracy; document intelligence; GUI agents",
    knownLimitations: "16 GB VRAM; trust_remote_code=True required",
    hfAdoption: "HF likes: 103 · 77,954 downloads/month · 25 finetunes",
    cloudEdge: "Cloud/server preferred", finetuning: true, dockerSupport: true,
    architecture: "ViT-MLP-LLM: InternViT-300M + Qwen2.5-7B; V2PE; Mixed Preference Opt.", maxTokens: "16384",
    paramsB: 8, numLayers: 28, numKvHeads: 4, headDim: 128, // Qwen2.5-7B backbone (published config)
  },
  {
    name: "InternVL3-2B", hfId: "OpenGVLab/InternVL3-2B", category: "Vision & Multimodal",
    year: 2025, yearLabel: "2025 (Apr)", params: "2B",
    tasks: ["Image Captioning", "Visual QA", "Document Understanding", "OCR", "GUI Grounding", "Video Understanding"],
    modelSize: "~4 GB", vram: "~4 GB BF16 · ~3 GB INT8",
    quantization: ["BF16", "BNB 8-bit", "AWQ/GPTQ (community)"],
    multilingual: "Multilingual via Qwen2.5-1.5B backbone", cpuSupport: true, commercial: true,
    origin: "China (OpenGVLab / Shanghai AI Lab)", maintained: true,
    serving: ["HF Transformers", "LMDeploy", "vLLM", "SWIFT"],
    benchmark: "Best-in-class 2B VLM; outperforms many 7B+ models on vision tasks",
    keyBenchmarks: "Best 2B VLM: OCR, DocVQA, ChartQA competitive; GUI grounding capable",
    recommendedUse: "Best edge/CPU VLM at 2B scale; document understanding; GUI agents",
    knownLimitations: "trust_remote_code=True required",
    hfAdoption: "Active — part of InternVL3 family (84 likes, 33 models)",
    cloudEdge: "Both (Edge/CPU suitable)", finetuning: true, dockerSupport: true,
    architecture: "ViT-MLP-LLM: InternViT-300M + Qwen2.5-1.5B; V2PE; Native Multimodal Pre-Training", maxTokens: "16384",
    paramsB: 2, numLayers: 28, numKvHeads: 2, headDim: 128, // Qwen2.5-1.5B backbone (published config)
  },
  // Speech & Audio
  {
    name: "pyannote speaker-diarization", hfId: "pyannote/speaker-diarization-community-1", category: "Speech & Audio",
    year: 2025, yearLabel: "2025", params: "~37M total pipeline",
    tasks: ["Speaker Diarization", "Speaker Segmentation", "Overlapped Speech Detection"],
    modelSize: "~150 MB total", vram: "~2–4 GB or CPU",
    quantization: ["FP32"],
    multilingual: "Language-agnostic", cpuSupport: true, commercial: false,
    origin: "France (pyannote.audio)", maintained: true,
    serving: ["Python API (pyannote.audio)", "HF pipeline"],
    benchmark: "SOTA DER on AMI, AISHELL-4, MSDWild, VoxConverse",
    keyBenchmarks: "DER improvements over pyannote 3.1 on all major diarization benchmarks",
    recommendedUse: "Production speaker diarization; meeting transcription; broadcast",
    knownLimitations: "Gated model (HF acceptance required); commercial license for production",
    hfAdoption: "Industry standard for speaker diarization",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Modular: segmentation-3.0 + WeSpeaker embeddings + clustering", maxTokens: "N/A",
  },
  {
    name: "DiariZen", hfId: "BUT-FIT/diarizen-wavlm-large-s80-md-v2", category: "Speech & Audio",
    year: 2025, yearLabel: "2025 (ICASSP)", params: "~73M (pruned WavLM Large + Conformer)",
    tasks: ["Speaker Diarization", "End-to-End Neural Diarization", "Multi-speaker Detection"],
    modelSize: "~300 MB", vram: "~4 GB or CPU",
    quantization: ["FP32"],
    multilingual: "Language-agnostic", cpuSupport: true, commercial: true,
    origin: "Czech Republic (BUT FIT)", maintained: true,
    serving: ["Python API"],
    benchmark: "ICASSP 2025 — SOTA at 80% WavLM sparsity",
    keyBenchmarks: "SOTA DER at 80% model sparsity (63.3M pruned WavLM Large)",
    recommendedUse: "Efficient diarization; research on pruned models",
    knownLimitations: "Hybrid EEND + clustering may struggle with large speaker counts",
    hfAdoption: "Research model, ICASSP 2025",
    cloudEdge: "Both", finetuning: false, dockerSupport: false,
    architecture: "Hybrid EEND + global clustering; WavLM Large pruned 80% + Conformer", maxTokens: "N/A",
  },
  {
    name: "TEN VAD", hfId: "TEN-framework/ten-vad", category: "Speech & Audio",
    year: 2025, yearLabel: "2025 (Jun)", params: "Very small (C-native + ONNX)",
    tasks: ["Voice Activity Detection", "Real-time Streaming VAD", "Conversational Voice Agent VAD"],
    modelSize: "<1 MB", vram: "CPU-only",
    quantization: ["INT8 (C-native)"],
    multilingual: "Language-agnostic", cpuSupport: true, commercial: true,
    origin: "TEN Framework", maintained: true,
    serving: ["C library", "ONNX Runtime", "Python bindings"],
    benchmark: "Sub-millisecond latency; purpose-built for real-time voice agents",
    keyBenchmarks: "<1 ms latency, designed for high-concurrency voice agent services",
    recommendedUse: "Real-time voice agents; streaming VAD; IoT/edge CPU-only",
    knownLimitations: "Proprietary architecture; no public parameter count",
    hfAdoption: "Growing in TEN framework ecosystem",
    cloudEdge: "Edge (primary)", finetuning: false, dockerSupport: true,
    architecture: "Deep learning streaming VAD, C-native with ONNX backbone", maxTokens: "N/A",
  },
  {
    name: "Silero VAD v5", hfId: "snakers4/silero-vad", category: "Speech & Audio",
    year: 2025, yearLabel: "2021–2025 (v5)", params: "~1–2M (LSTM-based)",
    tasks: ["Voice Activity Detection", "Speech Timestamps", "Single-channel VAD"],
    modelSize: "~2 MB (v5)", vram: "CPU-only",
    quantization: ["INT8", "ONNX", "JIT"],
    multilingual: "Language-agnostic (100+ languages)", cpuSupport: true, commercial: true,
    origin: "Russia (Silero team)", maintained: true,
    serving: ["torch.hub", "ONNX Runtime", "JIT", "C++ (ONNX)"],
    benchmark: "Industry-standard open-source VAD; v5 is 3× faster than v4",
    keyBenchmarks: "v5: 3× faster than v4; ONNX ~2 MB; sub-ms inference",
    recommendedUse: "Production VAD for any scale — streaming, edge, cloud",
    knownLimitations: "LSTM-based — less accurate on very noisy or unusual speech",
    hfAdoption: "Industry standard; millions of downloads",
    cloudEdge: "Both", finetuning: false, dockerSupport: true,
    architecture: "LSTM-based deep learning streaming VAD", maxTokens: "N/A",
  },
  {
    name: "Distil-Whisper large-v3", hfId: "distil-whisper/distil-large-v3", category: "Speech & Audio",
    year: 2024, yearLabel: "2024 (Mar)", params: "756M",
    tasks: ["Speech-to-Text Transcription (English)", "Long-form ASR", "Streaming ASR"],
    modelSize: "~1.5 GB (FP16)", vram: "~4 GB or CPU",
    quantization: ["FP16", "INT8 (OpenVINO)", "GGUF (whisper.cpp)"],
    multilingual: "English-only", cpuSupport: true, commercial: true,
    origin: "USA (Hugging Face)", maintained: true,
    serving: ["HF Transformers", "OpenVINO", "whisper.cpp", "faster-whisper"],
    benchmark: "6× faster than Whisper large-v3 with only 1% WER increase",
    keyBenchmarks: "6× faster than Whisper large-v3; 1% WER increase — best distilled ASR",
    recommendedUse: "Production English ASR; streaming transcription; latency-sensitive pipelines",
    knownLimitations: "English-only; accuracy slightly below Whisper large-v3",
    hfAdoption: "Very high adoption; millions of downloads",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Distilled Whisper large-v3; 2 decoder layers vs 32 in original", maxTokens: "N/A",
  },
  {
    name: "IndicConformer-600M-Multilingual", hfId: "ai4bharat/indic-conformer-600m-multilingual", category: "Speech & Audio",
    year: 2025, yearLabel: "2024–2025", params: "600M",
    tasks: ["Speech-to-Text (22 Indian Languages)", "Indic ASR"],
    modelSize: "~2.4 GB", vram: "~4 GB or CPU",
    quantization: ["FP32", "FP16"],
    multilingual: "22 official Indian languages", cpuSupport: true, commercial: true,
    origin: "India (AI4Bharat / IIT Madras)", maintained: true,
    serving: ["NeMo framework", "HF Transformers"],
    benchmark: "SOTA on IndicSUPERB across 22 Indian languages",
    keyBenchmarks: "SOTA IndicSUPERB — best multilingual Indic ASR",
    recommendedUse: "Indian language voice apps; 22-language ASR; Bhashini integration",
    knownLimitations: "NeMo dependency; Indian languages only",
    hfAdoption: "Leading Indic ASR model; Bhashini integration",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Conformer encoder + CTC/RNNT decoder; 600M params", maxTokens: "N/A",
  },
  {
    name: "Cohere Transcribe 03-2026", hfId: "CohereLabs/cohere-transcribe-03-2026", category: "Speech & Audio",
    year: 2026, yearLabel: "2026 (Mar)", params: "2B",
    tasks: ["Speech-to-Text (14 Languages)", "Diarization-aware Transcription", "Streaming ASR"],
    modelSize: "~4 GB", vram: "~6 GB",
    quantization: ["BF16", "INT8"],
    multilingual: "14 languages incl. English, French, Spanish, German, Hindi", cpuSupport: false, commercial: true,
    origin: "Canada (Cohere)", maintained: true,
    serving: ["Cohere API", "HF Transformers", "vLLM"],
    benchmark: "Competitive with Whisper large-v3 on multilingual benchmarks",
    keyBenchmarks: "Strong multilingual ASR with built-in diarization awareness",
    recommendedUse: "Multilingual transcription; enterprise voice pipelines; 14-language support",
    knownLimitations: "GPU required; 14 languages only",
    hfAdoption: "Recent release (Mar 2026); growing adoption",
    cloudEdge: "Cloud (primary)", finetuning: false, dockerSupport: true,
    architecture: "Encoder-decoder; 2B; diarization-aware training", maxTokens: "N/A",
  },
  // Translation
  {
    name: "IndicTrans2 Indic→En 1B", hfId: "ai4bharat/indictrans2-indic-en-1B", category: "Translation",
    year: 2024, yearLabel: "2023 (paper) · 2024 HF", params: "1.1B",
    tasks: ["Machine Translation (22 Indian Languages → English)"],
    modelSize: "~4 GB", vram: "~4 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "22 Indian languages → English", cpuSupport: true, commercial: true,
    origin: "India (AI4Bharat / IIT Madras)", maintained: true,
    serving: ["HF Transformers", "IndicTransToolkit", "Bhashini API"],
    benchmark: "SOTA Flores-200 Indic→English translation",
    keyBenchmarks: "SOTA Flores-200 Indic→En — best open model for Indian language → English",
    recommendedUse: "Indian language content translation to English; Bhashini integration",
    knownLimitations: "Indic→English direction only",
    hfAdoption: "Standard for Indic NLP translation tasks",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Transformer seq2seq 1.1B; trained on IndicCorp v2 + BPCC", maxTokens: "256",
  },
  {
    name: "IndicTrans2 En→Indic 1B", hfId: "ai4bharat/indictrans2-en-indic-1B", category: "Translation",
    year: 2024, yearLabel: "2023 (paper) · 2024 HF", params: "1.1B",
    tasks: ["Machine Translation (English → 22 Indian Languages)"],
    modelSize: "~4 GB", vram: "~4 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "English → 22 Indian languages", cpuSupport: true, commercial: true,
    origin: "India (AI4Bharat / IIT Madras)", maintained: true,
    serving: ["HF Transformers", "IndicTransToolkit", "Bhashini API"],
    benchmark: "SOTA Flores-200 English→Indic translation",
    keyBenchmarks: "SOTA Flores-200 En→Indic — best open English→Indian language translation",
    recommendedUse: "English content localization to 22 Indian languages",
    knownLimitations: "English→Indic direction only",
    hfAdoption: "Standard for Indic NLP translation tasks",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Transformer seq2seq 1.1B; trained on IndicCorp v2 + BPCC", maxTokens: "256",
  },
  {
    name: "IndicTrans2 Indic→Indic 1B", hfId: "ai4bharat/indictrans2-indic-indic-1B", category: "Translation",
    year: 2024, yearLabel: "2023 (Dec) · 2024 HF", params: "1B",
    tasks: ["Machine Translation (between 22 Indian Languages, no English pivot)"],
    modelSize: "~4 GB", vram: "~4 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "Any two of 22 Indian languages (Indic↔Indic)", cpuSupport: true, commercial: true,
    origin: "India (AI4Bharat / IIT Madras)", maintained: true,
    serving: ["HF Transformers", "IndicTransToolkit"],
    benchmark: "SOTA Flores-200 Indic↔Indic pairs",
    keyBenchmarks: "First SOTA model for direct cross-Indic translation without English pivot",
    recommendedUse: "Direct translation between Indian languages without English as pivot",
    knownLimitations: "Indic↔Indic only; no English endpoint",
    hfAdoption: "Unique capability for cross-Indic translation",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Transformer seq2seq 1B; unique Indic-to-Indic training corpus", maxTokens: "256",
  },
  {
    name: "TranslateGemma 12B IT", hfId: "google/translategemma-12b-it", category: "Translation",
    year: 2026, yearLabel: "2026 (Jan)", params: "12B",
    tasks: ["Machine Translation (100+ languages)", "Multimodal Translation (VLM-capable)"],
    modelSize: "~24 GB", vram: "~24 GB (multi-GPU recommended)",
    quantization: ["BF16", "INT4/INT8 (vLLM)"],
    multilingual: "100+ languages (Gemma backbone), instruction-tuned for translation", cpuSupport: false, commercial: true,
    origin: "USA (Google DeepMind)", maintained: true,
    serving: ["HF Transformers", "vLLM", "Google AI Studio"],
    benchmark: "FLORES-200 competitive across high-resource languages",
    keyBenchmarks: "Strong FLORES-200, unique VLM-capable translation model",
    recommendedUse: "High-quality translation with VLM understanding; 100+ language coverage",
    knownLimitations: "12B requires significant VRAM; slower than smaller translation models",
    hfAdoption: "Growing, Google backing",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "Gemma 2 12B, instruction-tuned for translation", maxTokens: "8192",
  },
  // Embeddings & Retrieval
  {
    name: "E5-large-v2", hfId: "intfloat/e5-large-v2", category: "Embeddings & Retrieval",
    year: 2022, yearLabel: "2022 (Dec)", params: "335M",
    tasks: ["RAG Passage Retrieval (asymmetric)", "Dense Retrieval", "Text Embedding"],
    modelSize: "~1.3 GB", vram: "~2 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "English-focused", cpuSupport: true, commercial: true,
    origin: "USA (Microsoft Research)", maintained: true,
    serving: ["HF Transformers", "sentence-transformers"],
    benchmark: "Strong BEIR; widely used in RAG pipelines",
    keyBenchmarks: "Competitive BEIR scores; best E5 single-language variant",
    recommendedUse: "Asymmetric RAG retrieval (query→passage); English production pipelines",
    knownLimitations: "English-focused; requires 'query: ' / 'passage: ' prefixes",
    hfAdoption: "Millions of downloads; widely deployed",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "BERT-large; contrastive pre-training on weakly supervised data", maxTokens: "512",
  },
  {
    name: "BGE-M3", hfId: "BAAI/bge-m3", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024 (Feb)", params: "568M",
    tasks: ["Dense Retrieval", "Sparse Retrieval (BM25-style)", "Multi-vector Retrieval (ColBERT-style)"],
    modelSize: "~2.3 GB", vram: "~3 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "100+ languages — gold standard for multilingual retrieval", cpuSupport: true, commercial: true,
    origin: "China (BAAI)", maintained: true,
    serving: ["HF Transformers", "FlagEmbedding", "sentence-transformers", "Ollama"],
    benchmark: "#1 multilingual retrieval on MIRACL, mBEIR, MTEB multilingual",
    keyBenchmarks: "MTEB multilingual: #1 · MIRACL: #1 · supports dense + sparse + multi-vector",
    recommendedUse: "Multilingual RAG; hybrid retrieval; 100+ language production",
    knownLimitations: "568M — larger than single-language alternatives",
    hfAdoption: "Very high; millions of downloads; gold standard for multilingual retrieval",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "XLM-RoBERTa; M3-Embedding: multi-functionality (dense+sparse+multi-vector)", maxTokens: "8192",
  },
  {
    name: "BGE-large-en-v1.5", hfId: "BAAI/bge-large-en-v1.5", category: "Embeddings & Retrieval",
    year: 2023, yearLabel: "2023 (Sep)", params: "335M",
    tasks: ["Dense Text Embedding", "Semantic Search", "RAG Retrieval"],
    modelSize: "~1.3 GB", vram: "~2 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "English-focused", cpuSupport: true, commercial: true,
    origin: "China (BAAI)", maintained: true,
    serving: ["HF Transformers", "FlagEmbedding", "sentence-transformers"],
    benchmark: "#1 English MTEB (at release); BEIR competitive",
    keyBenchmarks: "MTEB English: top-tier; BEIR competitive; widely used baseline",
    recommendedUse: "English semantic search; RAG embedding; production similarity search",
    knownLimitations: "English-focused; no sparse or multi-vector retrieval",
    hfAdoption: "Millions of downloads; one of the most deployed embedding models",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "BERT-large; contrastive + self-distillation training", maxTokens: "512",
  },
  {
    name: "BGE-reranker-large", hfId: "BAAI/bge-reranker-large", category: "Embeddings & Retrieval",
    year: 2023, yearLabel: "2023 (Sep)", params: "560M",
    tasks: ["Stage-2 Reranking in RAG", "Cross-encoder Relevance Scoring"],
    modelSize: "~2.2 GB", vram: "~3 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "English-focused reranker", cpuSupport: true, commercial: true,
    origin: "China (BAAI)", maintained: true,
    serving: ["HF Transformers", "FlagEmbedding", "sentence-transformers"],
    benchmark: "Strong BEIR reranking; standard English RAG reranker",
    keyBenchmarks: "BEIR reranking competitive; widely used production reranker",
    recommendedUse: "Stage-2 reranking in RAG pipelines; improving retrieval precision",
    knownLimitations: "English-focused; cross-encoder inference is slower than bi-encoders",
    hfAdoption: "Very high adoption in RAG pipelines",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Cross-encoder BERT-large; binary relevance classification", maxTokens: "512",
  },
  {
    name: "BGE-reranker-v2-m3", hfId: "BAAI/bge-reranker-v2-m3", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024 (Mar)", params: "568M",
    tasks: ["Multilingual Stage-2 Reranking", "Cross-encoder Relevance Scoring"],
    modelSize: "~2.3 GB", vram: "~3 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "100+ languages (BGE-M3 backbone)", cpuSupport: true, commercial: true,
    origin: "China (BAAI)", maintained: true,
    serving: ["HF Transformers", "FlagEmbedding"],
    benchmark: "Best multilingual reranker; built on BGE-M3 backbone",
    keyBenchmarks: "MIRACL reranking; mBEIR competitive; best multilingual reranker",
    recommendedUse: "Multilingual RAG reranking; 100+ language Stage-2 pipeline",
    knownLimitations: "Cross-encoder inference is slower than bi-encoder retrieval",
    hfAdoption: "Standard for multilingual RAG reranking",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Cross-encoder XLM-RoBERTa (BGE-M3 base); multilingual relevance", maxTokens: "8192",
  },
  {
    name: "jina-reranker-v2-base-multilingual", hfId: "jinaai/jina-reranker-v2-base-multilingual", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024 (Jun)", params: "278M",
    tasks: ["Multilingual Stage-2 Reranking", "Agentic RAG Reranking"],
    modelSize: "~1.1 GB", vram: "~2 GB or CPU",
    quantization: ["FP32", "FP16"],
    multilingual: "100+ languages", cpuSupport: true, commercial: false,
    origin: "Germany (Jina AI)", maintained: true,
    serving: ["HF Transformers", "Jina AI API", "sentence-transformers"],
    benchmark: "Competitive multilingual reranking; smaller than BGE-reranker-v2-m3",
    keyBenchmarks: "Multilingual BEIR competitive; designed for agentic RAG workflows",
    recommendedUse: "Multilingual reranking; agentic RAG; smaller model size preferred",
    knownLimitations: "Non-commercial license; slightly behind BGE-M3 reranker on accuracy",
    hfAdoption: "Strong Jina ecosystem adoption",
    cloudEdge: "Both", finetuning: false, dockerSupport: true,
    architecture: "XLM-RoBERTa cross-encoder 278M; multilingual relevance scoring", maxTokens: "8192",
  },
  {
    name: "Semantic Router", hfId: "aurelio-labs/semantic-router", category: "Embeddings & Retrieval",
    year: 2024, yearLabel: "2024", params: "Encoder-dependent (default: 22M MiniLM)",
    tasks: ["Utterance Similarity Routing", "Zero-training Intent Classification", "Agent Tool Selection"],
    modelSize: "Encoder-dependent", vram: "CPU-viable with small encoders",
    quantization: ["Encoder-dependent"],
    multilingual: "Depends on chosen encoder", cpuSupport: true, commercial: true,
    origin: "UK (Aurelio AI)", maintained: true,
    serving: ["Python library (pip install semantic-router)"],
    benchmark: "Zero-training routing via example utterances only",
    keyBenchmarks: "No dedicated model — uses any embedding model; zero-training semantic routing",
    recommendedUse: "LLM query routing; intent detection; tool/agent selection without fine-tuning",
    knownLimitations: "Accuracy depends on example utterance quality and chosen encoder",
    hfAdoption: "Growing; widely used in LLM routing frameworks",
    cloudEdge: "Both", finetuning: false, dockerSupport: true,
    architecture: "Encoder + cosine similarity + route matching; no dedicated router model", maxTokens: "N/A",
  },
  {
    name: "ColPali / ColVision Family", hfId: "vidore/colpali-v1.3", category: "Embeddings & Retrieval",
    year: 2025, yearLabel: "2024 (Jun) – 2026", params: "ColPali-v1.3: ~3B · ColQwen2.5: ~3B",
    tasks: ["Visual Document Retrieval", "Multi-vector Embedding (document page images)", "PDF-native RAG"],
    modelSize: "~6 GB", vram: "~8 GB",
    quantization: ["BF16", "INT8 (community)"],
    multilingual: "Multilingual (VLM backbone)", cpuSupport: false, commercial: true,
    origin: "France (CentraleSupélec / HuggingFace)", maintained: true,
    serving: ["HF Transformers", "byaldi library", "ColBERT engine"],
    benchmark: "#1 ViDoRe V1/V2/V3 visual document retrieval benchmarks",
    keyBenchmarks: "ViDoRe V1: #1 · V2: #1 · V3: SOTA — best visual document retrieval",
    recommendedUse: "PDF-native RAG without text extraction; visually-rich document retrieval",
    knownLimitations: "GPU recommended; ~3B makes edge deployment difficult",
    hfAdoption: "ICLR 2025 accepted; rapidly growing; new standard for visual RAG",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "PaliGemma/Qwen2-VL backbone + linear projection; multi-vector ColBERT-style", maxTokens: "N/A",
  },
  {
    name: "LFM2.5-Embedding-350M", hfId: "LiquidAI/LFM2.5-Embedding-350M", category: "Embeddings & Retrieval",
    year: 2025, yearLabel: "2025 (Jun)", params: "350M",
    tasks: ["Dense Retrieval", "Text Embedding", "Semantic Search"],
    modelSize: "~1.4 GB", vram: "~2 GB or CPU",
    quantization: ["FP32", "FP16", "INT8"],
    multilingual: "Multilingual (LFM backbone)", cpuSupport: true, commercial: true,
    origin: "USA (Liquid AI)", maintained: true,
    serving: ["HF Transformers", "sentence-transformers"],
    benchmark: "MTEB competitive; strong multilingual embedding at 350M",
    keyBenchmarks: "MTEB competitive at 350M scale with LFM2.5 architecture advantages",
    recommendedUse: "Efficient multilingual embedding; edge-compatible retrieval",
    knownLimitations: "Newer model; less battle-tested than BGE/E5 in production",
    hfAdoption: "Recent release; growing in LFM ecosystem",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "LFM2.5 architecture; 350M; dense embedding", maxTokens: "8192",
  },
  // Safety & Guardrails
  {
    name: "ShieldGemma-2B", hfId: "google/shieldgemma-2b", category: "Safety & Guardrails",
    year: 2024, yearLabel: "2024 (Jul)", params: "2B",
    tasks: ["Content Moderation", "Harm Classification (Sexually Explicit, Dangerous Content, Hate Speech, Harassment)"],
    modelSize: "~4 GB", vram: "~4 GB or CPU",
    quantization: ["BF16", "INT8", "GGUF (community)"],
    multilingual: "Multilingual (Gemma backbone)", cpuSupport: true, commercial: true,
    origin: "USA (Google DeepMind)", maintained: true,
    serving: ["HF Transformers", "vLLM", "Ollama"],
    benchmark: "SOTA content moderation for 4 harm categories at 2B scale",
    keyBenchmarks: "4-category content moderation: SOTA SafetyBench at 2B scale",
    recommendedUse: "Production content moderation; pre/post-inference safety filtering",
    knownLimitations: "Limited to 4 harm categories; binary classification only",
    hfAdoption: "Google backing; widely adopted in safety pipelines",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Gemma 2B; instruction-tuned for content policy classification", maxTokens: "8192",
    paramsB: 2, numLayers: 26, numKvHeads: 4, headDim: 256, // Gemma-2-2B (published config)
  },
  {
    name: "Llama-Guard-3-8B", hfId: "meta-llama/Llama-Guard-3-8B", category: "Safety & Guardrails",
    year: 2024, yearLabel: "2024 (Jul)", params: "8B",
    tasks: ["Content Safety Classification (13 MLCommons hazard categories)", "Input + Output Moderation"],
    modelSize: "~16 GB", vram: "~16 GB BF16 · ~8 GB INT4",
    quantization: ["BF16", "INT4/INT8 (vLLM)", "GGUF (community)"],
    multilingual: "Multilingual (Llama 3.1 backbone)", cpuSupport: false, commercial: true,
    origin: "USA (Meta AI)", maintained: true,
    serving: ["HF Transformers", "vLLM", "Ollama"],
    benchmark: "SOTA across 13 MLCommons hazard categories",
    keyBenchmarks: "13 MLCommons categories (S1–S13); SOTA safety classification; industry standard",
    recommendedUse: "Enterprise content safety; 13-category hazard detection; Meta pipeline",
    knownLimitations: "16 GB VRAM; gated (requires Meta EULA acceptance)",
    hfAdoption: "Industry standard; millions of downloads",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "Llama 3.1 8B; fine-tuned for 13-category MLCommons safety taxonomy", maxTokens: "8192",
    paramsB: 8, numLayers: 32, numKvHeads: 8, headDim: 128, // Llama-3.1-8B (published config)
  },
  {
    name: "Granite-Guardian-3.0-2B", hfId: "ibm-granite/granite-guardian-3.0-2b", category: "Safety & Guardrails",
    year: 2024, yearLabel: "2024 (Oct)", params: "2B",
    tasks: ["Multi-risk Detection (Harm, Social Bias, Jailbreaking)", "Prompt + Response Safety"],
    modelSize: "~4 GB", vram: "~4 GB or CPU",
    quantization: ["BF16", "INT8", "GGUF"],
    multilingual: "Multilingual (Granite backbone)", cpuSupport: true, commercial: true,
    origin: "USA (IBM Research)", maintained: true,
    serving: ["HF Transformers", "vLLM", "IBM watsonx"],
    benchmark: "Competitive with Llama-Guard; adds social bias + jailbreak detection",
    keyBenchmarks: "Multi-risk: harm + social bias + jailbreaking at 2B scale",
    recommendedUse: "Enterprise safety with IBM watsonx; multi-risk detection; jailbreak prevention",
    knownLimitations: "Smaller than Llama-Guard-3-8B; fewer hazard categories",
    hfAdoption: "IBM-backed; growing enterprise adoption",
    cloudEdge: "Both", finetuning: true, dockerSupport: true,
    architecture: "Granite 3.0 2B; multi-risk safety fine-tuning", maxTokens: "4096",
  },
  {
    name: "openai/privacy-filter", hfId: "openai/privacy-filter", category: "Safety & Guardrails",
    year: 2026, yearLabel: "2026 (Apr)", params: "1.5B (50M active)",
    tasks: ["PII Detection (Token Classification / NER)", "Privacy Filtering"],
    modelSize: "~3 GB", vram: "~3 GB or CPU",
    quantization: ["BF16"],
    multilingual: "English-focused", cpuSupport: true, commercial: true,
    origin: "USA (OpenAI)", maintained: true,
    serving: ["HF Transformers"],
    benchmark: "SOTA PII detection; open-sourced by OpenAI",
    keyBenchmarks: "Best-in-class PII detection; 50M active of 1.5B total (MoE-like)",
    recommendedUse: "PII scrubbing; privacy compliance (GDPR); data filtering pipelines",
    knownLimitations: "English-focused; NER-based (may miss context-dependent PII)",
    hfAdoption: "Very recent (Apr 2026); OpenAI provenance drives rapid adoption",
    cloudEdge: "Both", finetuning: false, dockerSupport: false,
    architecture: "Token classifier; 1.5B total / 50M active (MoE-like NER)", maxTokens: "N/A",
  },
  // LLM
  {
    name: "Qwen3-30B-A3B", hfId: "Qwen/Qwen3-30B-A3B", category: "LLM",
    year: 2025, yearLabel: "2025 (Apr)", params: "30.5B total · 3.3B active (MoE)",
    tasks: ["Instruction-tuned MoE LLM", "Reasoning", "Code Generation", "Math", "Tool Use"],
    modelSize: "~60 GB BF16 · ~15 GB INT4", vram: "~15 GB INT4 or ~60 GB BF16",
    quantization: ["BF16", "INT4/INT8 (vLLM)", "GGUF (community)"],
    multilingual: "Multilingual — 119 languages (Qwen3 backbone)", cpuSupport: false, commercial: true,
    origin: "China (Alibaba / Qwen Team)", maintained: true,
    serving: ["HF Transformers", "vLLM", "SGLang", "Ollama (GGUF)", "LMDeploy"],
    benchmark: "Competitive with Llama 4 Scout and Mixtral 8x22B at 3.3B active params",
    keyBenchmarks: "MATH, GPQA, LiveCodeBench: competitive with much larger dense models",
    recommendedUse: "Cost-effective large-scale reasoning; code gen; math at low activation cost",
    knownLimitations: "Full model 30.5B; needs INT4 for single-GPU; thinking overhead",
    hfAdoption: "Very high — part of Qwen3 family with large community",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "Mixture-of-Experts; 30.5B total; 3.3B activated per token; 64 experts", maxTokens: "32768",
    paramsB: 30.5, numLayers: 48, numKvHeads: 4, headDim: 128, // Qwen3-30B-A3B (published config)
  },
  {
    name: "Gemma 4 26B-A4B-IT", hfId: "google/gemma-4-26B-A4B-it", category: "LLM",
    year: 2026, yearLabel: "2026 (Apr)", params: "25.2B total · 3.8B active (MoE)",
    tasks: ["Multimodal Instruction-tuned LLM", "Vision + Text Reasoning", "Code", "Math"],
    modelSize: "~50 GB BF16 · ~13 GB INT4", vram: "~13 GB INT4 or ~50 GB BF16",
    quantization: ["BF16", "INT4/INT8 (vLLM)", "GGUF (community)"],
    multilingual: "140+ languages", cpuSupport: false, commercial: true,
    origin: "USA (Google DeepMind)", maintained: true,
    serving: ["HF Transformers", "vLLM", "Ollama", "Google AI Studio"],
    benchmark: "Competitive with Llama 4 Scout on vision + text benchmarks",
    keyBenchmarks: "MMMU, DocVQA, MathVista: competitive at 4B active MoE scale",
    recommendedUse: "Multimodal production workloads; vision + text reasoning at low inference cost",
    knownLimitations: "~50 GB full model; needs INT4 for consumer hardware",
    hfAdoption: "Apache 2.0; Google backing; high adoption",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "MoE VLM; 25.2B total; 3.8B active; image + text encoder", maxTokens: "8192",
  },
  {
    name: "LFM2.5-1.2B-Instruct", hfId: "LiquidAI/LFM2.5-1.2B-Instruct", category: "LLM",
    year: 2025, yearLabel: "2025 (Feb)", params: "1.2B",
    tasks: ["Instruction-tuned Edge LLM", "General Chat", "Task Completion"],
    modelSize: "~2.4 GB", vram: "~3 GB or CPU",
    quantization: ["BF16", "INT4/INT8", "GGUF"],
    multilingual: "Multilingual (LFM backbone)", cpuSupport: true, commercial: true,
    origin: "USA (Liquid AI)", maintained: true,
    serving: ["HF Transformers", "vLLM", "Ollama"],
    benchmark: "Best-in-class 1.2B instruction LLM",
    keyBenchmarks: "MMLU, MT-Bench: SOTA at 1.2B scale; Liquid Foundation Model advantages",
    recommendedUse: "Edge LLM; CPU-capable assistant; on-device inference",
    knownLimitations: "Small model — limited complex reasoning vs larger LLMs",
    hfAdoption: "Growing LFM ecosystem; strong results for size",
    cloudEdge: "Both (Edge primary)", finetuning: true, dockerSupport: true,
    architecture: "Liquid Foundation Model 2.5; 1.2B; instruction tuned", maxTokens: "32768",
  },
  // Code & Agents
  {
    name: "FastContext-1.0-4B-SFT", hfId: "microsoft/FastContext-1.0-4B-SFT", category: "Code & Agents",
    year: 2025, yearLabel: "2025 (Recent)", params: "4B",
    tasks: ["Code Exploration", "Repository Navigation Agent", "Codebase Q&A"],
    modelSize: "~8 GB", vram: "~8 GB · ~4 GB INT4",
    quantization: ["BF16", "INT4/INT8"],
    multilingual: "Multi-language programming (code-focused)", cpuSupport: false, commercial: true,
    origin: "USA (Microsoft Research)", maintained: true,
    serving: ["HF Transformers", "vLLM"],
    benchmark: "SOTA SWE-bench Lite for 4B-scale code navigation agents",
    keyBenchmarks: "SWE-bench Lite competitive at 4B scale; repo-level code understanding",
    recommendedUse: "Autonomous code agents; repository exploration; codebase Q&A",
    knownLimitations: "Code/agent-specific; not for general chat; requires structured prompting",
    hfAdoption: "Microsoft-backed; growing in agent framework integrations",
    cloudEdge: "Cloud (primary)", finetuning: true, dockerSupport: true,
    architecture: "Phi-based 4B; SFT for code exploration and repository navigation", maxTokens: "8192",
  },
];
